ntacamp/404.notrollsallowed.com

- index.html
Let's figure out why this camp can not be found.
> Intro: Camp Not Found

- 404.txt
This talk is likely to span 30-45 minutes while covering the following topics:
* What happens when one uses a payment card at a POS/ATM;
* An abridged version of responsibilities of all parties involved in making the payment succeed or fail;
* How can the owner of a payment card (no, very likely, you are not the owner -- you are only the holder of the card, while some bank-link institution is the owner) vanish, move elsewhere, and what happens to the card and pending payments at that time.
Save for some portions which better remain private for the sake of the companies which are still very active, the talk is based on an actual experience doing a `308 Permanent Redirect` of sorts. Over a span of 6 hours. And then again, over a similar time period, that time succeeding more.
> (jbutkus) How Come The Bank is 404

- 404.txt
Pranešiu pranešimą kaip man sekėsi nuo nulio įgyvendinti RFID duomenų nuskaitymo algoritmą iš Lietuvos paso ir ID kortelės. Taip pat papasakosiu su kokiais sunkumais susidūriau bebandydamas įgyvendinti pasirašymo algoritmą su Lietuvos ID kortele. Atsivešiu smart card ir RFID skaitytuvų demonstracijai, o jei bus susidomėjusių, galėsim dar ir padaryti workshopą.
Komunikacija su smart card ir RFID loginiame lygmenyje vyksta vienodai, keturių ir daugiau baitų ilgio komandomis, skiriasi tik fizinis ir transporto lygmuo. Komandų formatą, duomenų kodavimą, duomenų struktūras reglamentuoja įvairūs standartais, kurių kiekvienas remiasi bent keliais kitais. Mano tikslas buvo juos visus suprasti ir įgyvendinti kode tiek, kiek reikia duomenų iš kortelės nuskaitymui. Pasiektas rezultatas buvo …
> Komunikacija su ID kortele nuo nulio: RFID ir el. parašas

- 404.txt
We've all been in the situations, where after endless hours of debugging something you've been working on and been continuously looping through various stages of acceptance, everything becomes dull. Requests are timing out without any reason, code looks like the output from /dev/random, and Paxos doesn't make any sense either. 
It is an open invitation to stop looking for explanations where they're not necessarily being found. Grab the pair of your most comfy sneakers, moisture-wicking t-shirt, a bottle of water, and follow the thuds into the night while dancing your problems away. There's no space for wicked thoughts, doubt, or worry when the senses are beset.
> (csh) When That Request Finally Times Out

- 404.txt
Šį pranešimą galvoju padaryti kaip kokią standup komediją apie sėkmės ir nesėkmes, kuriant išmaniuosius namus. Dalykai, kurie (ne)prigijo ir (ne)rekomenduoju:
- Porą DIY sensorių (cloud/non cloud based; atsinešiu keletą į vietą, ką esu sulipdęs)
- Namų serveriukas ant RPi 4, kuriame sukasi Grafana, InfluxDB, Telegraf, Mosquitto MQTT.
- Grafanos dashboards sensorių duomenų vizualizacijai
- Hass.io (Home Assistant)
- Google Home, 
- Home smart (IKEA)
- Xiaomi autonominiai siurbliai
- Kiti Xiaomi sensoriukai
**Kadangi ne viskas visada puikiai (su)veikia, tai galvojame padaryti tai kaip mini komediją/standup'ą. Turime 0 standup'inimo patirties, bet hey! visada gi būna pirmas kartas. Blogiausiu atveju - padarysime standartinę rimtą prezentaciją ir rimtai viską papasakosime. Bet tada jūs …
> Smart Home: Sėkmės ir nesėkėmės, kuriant išmanius namus

- 404.txt
- index.html
Norėčiau prisidėti kepant burgerius, tik nežinau ar sugebėčiau visiems 100-150 iškepti. Produktus galėčiau donate'int camp'ui, bet labai reikėtų rankų kepant viską.
> Burgers for (possibly) everyone

- 404.txt
**TL;DR**
I do all kinds of stuff with laptop parts and want to show all the old and new ways of reusing them in your projects.
**Long Version**
Apart from the obvious stuff (HDDs, RAM sticks etc.) I've personally reused keyboards (as external keyboards with a Teensy controller+custom PCB), LCD panels as additional monitors, broken LCD panels as lightboxes, as lasercutting materials, and I've reused the laptop LED strips for lighting. I've also reused a laptop touchscreen as a USB touchscreen together with a FullHD LCD panel, essentially making an external portable touch-enabled monitor. I've rebuilt working laptop motherboards into embedded PCs of sorts in various projects, and I stockpile broken motherboards as component sources for all kinds of projects (the N-FETs are quite good, but …
> Laptop Casting: reusing all the laptop parts

- 404.txt
Sitaucija tokia, kad reikia baldų, greitai, pigiai, hipsteriškų, ar ne..? Sprendimas yra! Turiu įvairių dizainų, idėjų, minčių ir praktinio įgyvendinimo pavyzdžių. Parodysiu renderius, softinius tools'us, pasidalinsiu patirtimi, kokios garažo įrangos reikia tokiems baldams, kur papigiai gauti medžiagų, linkai į pigią ir veikiančią įrangą iš aliexpress.com.
Baldų stilius ala "skandinaviškas" su hipsterišku posūkiu a.k.a "industrial".
> "Skandinaviško" stiliaus baldai garaže, pigiai

- 404.txt
Hands on Rope bondage workshop for anyone interested. Lets learn essential safety rules, then familiarize with building blocks of traditional techniques and combine those to tie your partner or yourself. Untying is optional ;-)
> Safe and practical intro to Rope Bondage

- 404.txt
In this presentation I'll present my long-running project to create a first person view for a RC plane. This is going to be a progress report with thought process, stuff already done and still pending to do.
> Homemade first person view for a RC plane. Progress report

- 404.txt
Instarem (NIUM) dirbau su bankais / payment sistemomis. Dabar žinau kaip veikia elektroninų pinigų įmonės iš techninės pusės. Noriu pasidalinti patirtimi. Daugiausia WTF'ais kaip naujos kartos sinžinierius apie tas senovines sistemas. Kas mane išvertė iš koto. Kas padaryta gerai, o kas blogai. Greičiausiai paliesiu ir sąsajas su dabartiniu verslu - shipping'u. Techniškai shipping'e galėtų būti viskas identiškai, bet praktikoje yra naudojami visiškai skirtingi sprendimai.
> Experience with payment systems (SEPA, UK, Asia, SWIFT)

- 404.txt
Žmonės šneka, kad vangiam pasipriešinimo judėjimui šiuolaikinėje Baltarusijoje labiausiai trūksta uždegančių ir sutelkiančių dainų. Pasiklausykime, ką groja uždraustos baltarusių grupės, ir kaip jos save pateikia. Kaip etniniame chaose, istorijos vingiuose ir sapnuose apie revoliuciją, blaškantis tarp Lenkijos, Lietuvos ir Ukrainos, bando įžvelgti savastį. „Būk bailiu, balsuok už ūsus!“
> Pasidaryk pats dainuojančią revoliuciją: sapnai apie nacionalinę tapatybę Baltarusijoje

- 404.txt
Having recently started using MacOS after years of Linux,
I have spent considerable amount of time to make UX in MacOS
as close to the setup I have in my Linux box.
Will talk about convenient ways of synchronizing dotfiles and
shell history across multiple computers. As well as customizing
MacOS installation such as remaping keys globally and then
mapping them back in particular applications.
Also will talk about CLI tools that work great on both Linux and
MacOS.
> Uniform UX across Linux and MacOS environments

- 404.txt
What math lies behind a simple glitch cam? Small demo, short story, and glitches, glitches everywhere.
> Using math to make something pleasant to look at

- 404.txt
I will share my plan (not real experience yet - thanks pandemic!) for ways to
make life easier on a (small) farm. I will show you what FOS{H,S} can do for
us in this field.
> Smart Hom^WFarm

- 404.txt
Informatyvus pranešimas apie mėsos vartojimo istoriją, kainodarą, rinkodarą ir įtaką klimato kaitai
> "Mėsonomika": mėsos ir pieno istorija, politika ir ekonomika

- 404.txt
Origami - japoniškas popieriaus lankstymo menas. Užsiėmimo metu papasakosiu apie šį meną ir norintiems parodysiu kaip lankstyti keletą modelių.
> Origami: Kas tai per menas ir užsiėmimai

- 404.txt
**Thursday (Get your feet wet)**
- [Rambynas](https://www.play4n4.com/artists/rambynas) (tropical dj set)
- shvytejimas (industrial, ebm)
- [csh: when that request finally times out](https://github.com/ntacamp/404.notrollsallowed.com/pull/4) (cardio)
> Performances: Thursday activities 

- 404.txt
**Friday (Four to the floor)**
- [Rambynas](https://www.play4n4.com/artists/rambynas) (dj set)
- [SMPL SMPL](https://www.play4n4.com/artists/smpl-smpl) (live set) 
- [Jack Krass](https://www.play4n4.com/artists/jack-krass) (live set)
- TK-1 (dj set)
> Performances: Friday activities

- 404.txt
**Saturday (ambient night)**
- [Rambynas](https://www.play4n4.com/artists/rambynas) (ambient set)
- [csh](https://www.mixcloud.com/thecsh/) (live ambient set, featuring sounds of the camp)
> Performances: Saturday activities

- 404.txt
- index.html
Pristatymas: The right environment for fast and simple development.
Pristatysiu ir pasidalinsiu kaip pasidaryti programavimo aplinką, kuri taupo laiką, padaro "on-boarding'ą" paprastesnį bei integruojasi su Phabricator'iumi. Tai pat norėsiu padiskutuoti su klausytojais, kaip tai padaryta pas juos, kodėl pasirinktas vienas ar kitas variantas bei pakalbėti apie padarytas klaidas ir kaip jų išvengti.
> The right environment for fast and simple development

- 404.txt
Wakeboard’inti pradėjau praėjusią vasarą. Tuo metu pačiai kilo daug klausimų – nuo bendrų dalykų (pvz., kuri sistema – 2 ar 5 bokštų – geresnė pradedantiesiems) ir įrangos (kaip išsirinkti savo lentą, batus, hidriaką) iki technikos (kuria koja – dešine ar kaire – plaukti, kaip iš vis teisingai stovėti ant lentos, kaip išmokti apsisukti, kaip atlikti pirmuosius triukus). Tai noriu pasidalinti savo atradimais, iššūkiais, do's and don'ts, ką išmokau/ko neišmokau a.k.a. what can go wrong, nes sakoma, kad kristi ant vandens = kristi ant asfalto 🙈🙊
> Wakeboarding 101

- 404.txt
Pridedu prie pranešimų, bet čia labiau workshop, kai sutems.
* KMS - Kauno makerspace
> Dangaus šviesulių stebėjimas teleskopu

- 404.txt
Mano questas nuo (nealkoholinio) alaus ir čipsų link špinatų ir salotų - kaip numečiau 12 kg per 4 mėn ir pakeičiau savo santykį su maistu.
Šnekėsiu apie angliavandenius, baltymus, riebalus, vitaminus ir mikroelementus ir kodėl kalorija nelygu kalorijai.
> Mityba geekiškai: kas ta ketozė ir kodėl kalorijos skiriasi

- 404.txt
Quick overview and some of the practical applications for getting system information by exploring /proc mount.
From hardware (cpu, memory, network) up to process information - we'll go though layout, contents, possible pitfalls while reading information and some of the shortcomings.
> Added topic "digging for information in procfs"

- 404.txt
Žolės laistymas - labai užknisantis ir pastovios priežiūros reikalaujantis darbas, todėl nusprendžiau jį automatizuoti. Tiksliau padaryti taip, kad išvis nereikėtų apie jį galvoti.
Papasakosiu kaip programuotojui sekėsi susitvarkyti su žemės kasimo darbais, vandens pralaidumo skaičiavimais, elektronikos der(g)inimu.
> Autonominė žolės laistymo sistema

- 404.txt
Dūmų mašina miške, kuri gamina... Monster Fog!
> Monster Fog Machine

- 404.txt
Pripjaustėm trafaretų iš atliekamų med. skydelių broko, atsivežk savo maikę - ir pasidaryk NTA 2020/404 maikę pats.
Bus kelių spalvų purškiamų tekstilinių ir įprastų akrilinių dažų, su pakankamai atsargumo visai įmanoma pasigamint ir turėt.
Concept ref: https://i.imgur.com/8wbkPN6.jpg
> NTA t-shirt DIY

- 404.txt
Kas tie sintezatoriai? Kaip juos priversti veikti kartu? Ir išvis kad tas MIDI?
> Synths, Midi and FX. My path to wiring everything together

- 404.txt
Kaip ir kodel as gaminau gulima dvirati (recumbent bicycle), su kokiais sunkumais ir ipatybem teko susidurt, ir viskas ka jus norejot zinot apie dviraciu isradinejima nuo remo metalo lydiniu iki vidiniu pavaru stebules parinkino.
> Kaip aš pasigaminau gulimą dviratį

- 404.txt
ženklų atvaizdavimas naudojant dujinius degiklius. Trumpas pristatymas ir interaktyvi demonstracija. (technarium)
> PR38 bLED - Blaze Light Emitting Display 

- 404.txt
Degustacijos metu ragausime 5 neališkus alus, gilinsimės į jų stilių subtilybes bei aiškinsimės, kas išviso gali ir negali būti laikoma alumi. 
Trukmė: iki 1val.
Apribojimai: dalyvauti galės 10 suaugusių žmonių.
Kodėl tai darau: Keletą metų sukuosi alaus pasaulyje, su juo dirbu, domiuosi, geriu ir gyvenu – atėjo laikas pasidalinti šiuo gėriu su kitais.
> (Ne)alaus mini degustacija

- 404.txt
A workshop centered on making a player character for D&D 5e. Complete with backstory, abilities and more.
> Making your first D&D 5e player character

- 404.txt
I'll share my experience on reverse-engineering document scanners during past 1.5 years. What worked, what did not and what I learned from all of this. A lot of time will be spent discussing challenges I had with the pretty horrible legacy code base that I had to integrate my work into.
> What I learned from reverse-engineering document scanners

- 404.txt
Pasakosiu apie foto hakus ir tai, kaip reikia pasiruošti norint pagaut gerą kadrą. Kaip pasigaminti adapterį fotoparatui prisukt prie mikroskopo ir pan.
> Gamtos fotografija - kas slepiasi už gero kadro

- 404.txt
Kosmologija - tai fizikos šaka tirianti būtent visatos makroskopinę evoliuciją. Tikriausiai visi girdėjome kad pagrindinė teorija, kodėl mūsų realybė egzistuoja - nes kažkada neatmenai senai vyko toks didžiausias didysis sprogimas, kiti dar gal net pamenam kad visatos amžius sakoma yra 14 milijardų metų. Kaip mes tai galime žinoti? Ir kodėl mes tikime tokia 'teorija'? Pilnoji, gan ne 'pop' moksliška istorija turi daug daugiau detalių bei net baisių ir sielą valgančių matematinių lygčių, tačiau be jų negalima įsigilinti į šiuos klausimus, o betkoks supratimas lieka tik pasakiška neįtikinama pasaka.
Tad šiame pranešime laukite daug sulaužytų stereotipų apie jūsų įsivaizduojamą fizikos pasakų pasaulį apsivijantį visatos pradžią.
> Cosmology 101 - Kodel visatai būtent 14 milijardų metų ir kitkas

- 404.txt
Saulė (11m) praves workšopą ir kiekvienas galės pasidaryti sau apyrankę iš lazeriu pripautų karoliukų (iš akrilo likučiu - GREEN!!)
> Saulė (11m) praves workšopą ir kiekvienas galės pasidaryti sau apyrankę iš lazeriu pripautų karoliukų (iš akrilo likučiu - GREEN!!)

- 404.txt
Sun is the only astronomy object you can observe during daytime. Normally it is too bright to look at it by bare eye. Looking at it through optics would lead to instant blindness. But using special filters, astronomers can observe the Sun in it's real size as well as using optical devices. We will observe the Sun and clouds through 10x magnifying binoculars. Sun spots at the moment are quite minimal, but many interesting colors are promised!
> Astronomical Sun observation

- 404.txt
Pasakosiu, kaip rašiau skriptą, kuris iš Ežio saito traukė informaciją apie sąskaitos likučius tam, kad galima būtų juos parodyt žmogui patogiu būdu ant Nokios, o gavosi taip, kad radau pažeidžiamumą Ežio appse.
> Mano mamos Nokia ir kaip radau pažeidžiamimą Ežio appse

- 404.txt
Presentation shortly describes what are CPU emulators and how to start writing one.
> Add presentation "How to write a CPU emulator"

- 404.txt
My story about first Lithuanian unmanned high altitude balloon and it's 
70+ day journey around the planet Earth. Learn how to build and fly your own
pico floater balloon and what are the key factors to successful global 
circumnavigation.
Project coverage: 
* https://twitter.com/kelionebalionu
* https://facebook.com/kelionebalionu
> Ham radio: flying a high altitude balloon around the Earth

- 404.txt
Recently I've build few mechanical split keyboards for myself and friends. 
This process involves few steps:
- Choose the model
- Decide which switches to use
- Pick keycaps (it is more complex task than I initially thought)
- Source parts
- Assemble
- Make cables
- Flash the firmware
- Choose the model...
I am going to descrive each of the steps, share pitfalls I've faced, give some advises and finally explain what is the motivation behind this.
> Added topic: Building mechanical keyboards

- 404.txt
Pranešimo tema:
Papasakosiu apie CNC1419 (~350 €) vertės mini frezavimo/"drožimo" staklytes ir minimalius patobulinimus kurie leidžia graviruoti ir frezuoti spalvotus metalus. Papasakosiu apie softo pasirinkimo triūsą ir kokį softą vis tik išsirinkau.
Potemės:
Mechaninės CNC1419 savybės ir racionalūs patobulinimai;
Atvirojo kodo GRBL CNC valdiklio firmware'o nustatymai features'sai (https://github.com/grbl/grbl);
UGS Platform CNC valdymo programos džiaugsmai (https://winder.github.io/ugs_website/guide/platform/);
Vectric Aspire CAM softas bendriems CAM darbams;
FlatCAM galimybės ir workflow PCB frezavimui (https://github.com/Denvi/FlatCAM);
Know How Sharing:
Open diskusija/žinių dalinimasis prie alaus/kavos po pranešimo apie DIY CNC, nuo CNC blynų kepimo iki CNC plazmos ir t.t.
Open …
> CNC1419 (~350 €) vertės mini frezavimo/"drožimo" staklytės

- 404.txt
- index.html
Pasidalinciu savo patirtimi gerinant efektivumą su klaviatura.
Ka galima daryti, ka verta daryti. Klavišu remapingas, custom layouts, new shortcuts, macros, automation...
Prezentacijoje parodysiu kaip susikonfiguruoti savo klaviaturą patogiam tekstų(anglu ir lietuviu) ir programų rašymui.
> Keyboard hacking. (custom layout, remaps, automation.)

- 404.txt
Devų aplinkoje nuolat kalbama apie kodo kokybę ir neišmatuojamą to naudą. Iki tiek, kad tai praktiškai siekia religinį lygį.
Tuo tarpu versle dažniau laimi ne idealiai padaryti projektai, o "just good enough". Nes jie juda greičiau pirmus kelis metus (long term aišku kenčia).
Kaip rasti teisingą balansą. Kiek ateities galima ir reikia aukoti vardan greičio trumpuoju periodu. Kodėl geresnis kodas nebūtinai reiškia sėkmingesnę įmonę.
> Pabuskit! - kodo kokybė niekam neįdomi

- 404.txt
Trumpai papasakosiu kaip patobulinti **GM** (Game Master) skills, tokius kaip worldbuilding, railroading. Aptarsiu cooperative storytelling svarba per **TTRPGs** (Tabletop Roleplaying Games).
> How to be a great GM, the art of cooperative storytelling

- 404.txt
Will run you through what it takes to become a "Youtuber" or rather why it's easier AND harder than you think - at the same time.
> Youtube is hard. 1yr experience

- 404.txt
Pripjausim daug visokių dalykėliu su lazeriu ir leisim vaikams pakonstruoti - berniukams lėktuvus ir mašinytes - mergaitėms lėlyčių stalus ir karoliukus ...
Ir daug visokių kitokių smulkių dalykėlių ...
> Workshop for kids - laser cut toys, bracelets

- 404.txt
Mes įsivaizduojame ęsantys racionalios būtybės... kai iš esmės visi gimstame "bugovi".
Žmonių psichologija ir mąstymas evoliucianavo ilgus tukstantmečius, tačiau mes, kaip žmonija, neatpažįstamai pakeitėm savo aplinką ir socialinę hierarchiją per pastaruosius 2000 metų. Ko pasekoje - pagal nutylėjimą ęsame stebėtinai blogai prisitaikę funkcionuoti modernioje visuomenėje.
Papasakosiu savo kelionę nuo eilinio žmogaus iki suvokimo, jog net keista, kaip žmonių civilizacija vis dar veikia su tiek problemų žmogaus psichologijoje, kodėl šis suvokimas yra gerai ir ką su juo veikti.
> Kaip aš atradau, jog esu idiotas ir rekomenduočiau tai visiems

- 404.txt
Trumpa introdukcija į gyvenimą su aparatu, 1967 metais išrinktu Europos metų automobiliu. O vėliau tapusiu labiausiai paplitusiu DIY automobiliu SSRS ir už jos ribų. Renginio vietoje galima bus iš arti pamatyti vieną iš pavyzdžių, kad Lada yra tikrų tikriausia kasdienė mašina.
> Italo (LADA automobilio) nuotykiai SSRS

- 404.txt
I recently orthophotographed 2.9km² from the highest allowed altitude
for unrestricted drone flights (=120m), and made a map using these
photos.
In this presentation I will briefly explain the orthophotography part
and elaborate on how I made the map. Or I will elaborate on the
orthophotography (and flying) and briefly explain how I made the map.
Either way, you will see the drone, the map, and will know where to
start if you decide you want one too.
> Making maps using a consumer drone

- 404.txt
> Better title / content

- 404.txt
Pranešimas apie kambarinių augalų priežiūrą pradedantiesiems.
> Kaip nustoti žudyti savo fikusą

- 404.txt
Trumpai apžvelgsiu ką galima pasidaryti su Home Assisant nerašant kodo. Kalbėsiu apie:
* CO2 kiekio sekimą ofise
* automatinių vartų pavertimą išmaniais
* oro rekuperatoriaus valdymą
* asmeninių įrenginių apjungimą į VPN
> PR69 Išmaniai išmanūs namai nerašant kodo

- 404.txt
Presentation about largest Cyber security exercise in the world called "Locked Shields". What it takes to participate in such event, how it is conducted and what lessons could be learned to be applied in "real world" on a daily basis.
> Lessons learned during NATO cybersecurity exercise

- 404.txt
Kitoks budas kurti istorijas nestandartineje platformoje.
Kai 04:20 ryto dar sėdite youtube ar twitter ir randate kažką labai labai neaiškaus, gal tai nėra tik “werid side of youtube”, gal tai ARG? ARG- alternate reality game : alternatyvios realybės žaidimas: tai interaktyvus nestandartinės interneto platformos pasakojimas, kuris naudoja realųjį pasaulį kaip platformą ir jo žaidėjus kaip būda vystytis toliau, neigiantis apie “žaidimo” egzistavimą. Papraščiau: siaubo elementų turintis galvosūkis ar pasakojimas vykstantis realiu laiku ten youtube ar twitteri.
> ARG - Alternatyvios realybės žaidimas

- 404.txt
Tensegrity Structures: iš anksto įtemptos strypinės-vantinės konstrukcijos.
Dirbtuvės vaikams ir vyresniems vaikams apie mechanines jėgas ir meną.
Karolina & Romas
> Tensegrity Structures Workshop

- 404.txt
I'm volunteering for a health care service, creating a program to predict hypertension risks, and want to share some observations made when developing applications for the real world industry.
> Programming for goverment health care - the lessons learned

- 404.txt
Susipažinsim su Linux konteineriais iš arčiau:
* Kas tie Linux konteineriai?
* Kodėl ir kada jie atsirado?
* Kaip veikia Docker? 
* Pasileisim konteinerį be Docker
> Linux konteineriai

- 404.txt
Papasakosiu kaip iš naujo prisijaukinau juostinę fotografiją per karantiną ir ko išmokau pakeliui - nuo fotoaparatų remonto iki visokių įdomių praktinių (ir nelabai) know-how.
> Jumping into the weird end of the pool: juostinė fotografija

- 404.txt
Kaleidoskopų dirbtuvės. Medžiagų turėsiu tik 20čiai kaleidoskopų
> Kaleidoscope workshop

- 404.txt
Papasakosiu kaip sekėsi pasigaminti hidroponikos robotą ir kas išaugo ;-)
> Hidroponinis pomidorų auginimas ant palangės 

- 404.txt
Circumventing internet services censorship imposed by governments, ISPs or malicious interest groups.
We will look what are possible ways to build robust service discovery and evasive service providers.
> Workaround censorship for your services

- 404.txt
Jeigu alus yra tavo pašaukimas, arba niekada neatsisakai n-tojo bokalo - kviečiu patikrinti savo ilgus metus kauptas žinias 3 turų protmūšyje! Komandas galės sudaryti nuo 2-4 žmonių, o registracija vyks vietoje. :) Laimėtojų laukia kokybiškas skystas gėris, todėl patariu šias likusias dienas atidžiai ragauti savo gėrimus ir ruoštis protmūšiui!
> Alaus protmūšis

- 404.txt
Atsivesiu ZEISS mikroskopa (x10-x100) su live streamu i plansete/laptopa.
Priegriebsiu keleta meginiu is terariumu vandens, mirkytu samanu vandens, jei spesiu - koki grazu pelesi.
Galesim semt ezero vandeni, tuliko vandeni - apziurinet anything in great details, bet TIK su mano prieziura ;]
Workshopas?
> Mysterious Life Under Microscope

- 404.txt
Gūdžiais pandemijos žiemos vakarais su draugais sugalvojome pasidaryti talentų vakarą.
Kiti mokėjo groti įvairiais instrumentais ar šiaip kažką idomaus suvaidinti, bet iš dalykų, ką galima būtų
parodoti netechniniems žmonėms per video susitikimą, man (programuotojui) sugalvoti buvo sunku.
Ir tada prisiminiau pusiau juokais pasakytą posakį `jis groja kompu`.
Savaitę pasigilinus ir gimė mano pirmieji [Live Coding Music Sync](https://sonic-pi.net/).
Pranešime pristatysiu (ar ir pademonstruosiu):
* `Live coding music Sync` koncepciją
* kuo tai skiriasi/panašu nuo Spotify ar fizinio DJ pulto
* kaip [Sonic Pi](https://sonic-pi.net/) panaudoti meninių idėjų perteikimui ar/ir programavimo mokymuisi
* bei su kokiais techniniais iššūkiais susidūriau bandydamas viską pasileisti
> Sonic Pi, arba kaip programuotojai gali groti su kompu

- 404.txt
Papasakosiu kaip sugalvojau pasidaryti 34 klavišų klaviatūrą, su kokiomis problemomis susidūriau, kaip naudotis tokia klaviatūra ir kitus susijusius dalykus.
Ferris Sweep klaviatūros puslapis:
https://github.com/davidphilipbarr/Sweep
Ferris Sweep QMK puslapis:
https://github.com/qmk/qmk_firmware/tree/master/keyboards/ferris/sweep
Mano surinkta Ferris Sweep klaviatūra:
> Papasakosiu apie tai kaip pasidaryti ir naudoti 34 klavišų klaviatūrą.

- 404.txt
A story of how we use low-flying helicopters, precision lasers, ultra-high-res cameras, satellite internet and other cool gadgets to ensure you have uninterupted power all-year-long.
> The unheard world of power line inspections

- 404.txt
- index.html
Pranešimas apie kūdikių edukaciją:
- Pristatysiu Glenn Doman ir Makoto Shichida mokančias skaičiuoti kortelių metodikas, jų skirtumus ir privalūmus. Supažindinsiu, - Kaip edukuoti ir kaip teisingai pasigaminti priemones.
- Aptarsiu mokymo skaityti būdus (kortelių, daugiajutiminį ir paprastajį (native) metodą).
- QA
Subalansuota būsimiems tėvams bet tinka ir kitiems
> Kūdikių edukacija flash metodu

- 404.txt
Beveik 5 metai gaudant veja Lietuvoje su jegos ativarais. Trumpai pristatysiu pati sporta, taciau didziausia demesi skirsiu pamokom, kurias ismokau ir ko realiai reiktu tiketis
> Kitesurfing. Bandysiu atkalbėt ir papasakosiu kaip pradėti

- 404.txt
In this talk I will approach bike performance like computer performance and approach like any optimization project. Using watts as main metric to reduce the energy required to propel your vehicle forward. I will talk about aerodynamics, rolling resistance, drive chain efficiency, weight and of course speed.
> Improving your bike performance

- 404.txt
Svajojate dirbti kompiuteriu be pelės ir klavietūros? Nnorite perskaityti kolegos mintis ar jausmus? Tačiau mintis apie Musko fyškę smegenyse gąsdina ? :) OpenBCI - kaip tik Jums!
Šio pristatymo metu supažindinsiu su šiuo gadgetu, panaudojimo galimybėmis, pagrindiniu software stack'u bei didžiausiais iššūkiais bandant šį daiktą panaudoti realiame pasaulyje.
> Open-source Brain to Computer interface

- 404.txt
Organizuosiu "aklą" alaus testą. Rinksime geriausią produktą ne pagal etiketę, o pagal skonį.
> Beer blind test

- 404.txt
Šiais metais vėl norėčiau prisidėti prie camp'o gaminant visiems valgyt. Galvoju apie plėšytos kiaulienos dešrainius (su sūriu ir kopūstų salotomis)
> Maistas visiems!

- 404.txt
Papasakosiu kaip ieškojau webcam'ų ir kaip iš jų video su ffmpeg gaminau timelapse'us. Pamėginsiu parodyti rezultatus. :)
> Kaip iš internete rastų webcam'ų gaminau timelapse video

- 404.txt
Atsivežk vienspalvius marškinėlius ar kitą drabužį ir užsidėk 404 Camp logotipą ant jų!
Marškinėlius klijuosim šilkografijos būdu. Šilkografija - arba trafaretinė spauda - tai spaudos būdas, kai vaizdas dažais pernešamas per trafaretą ant norimo gaminio. Paskui visi padėkosim @RoCkaZ už įrangą ir dažus!
> DIY 404-camp t-shirt workshop

- 404.txt
Aš kūriu Artą žaidimams ir papasakosiu apie kūrimo procesą.
> Art'o kūrimas žaidimams

- 404.txt
I will be talking about keyboard layouts, why you should consider the alternatives and how to learn them.
> QWERTY's flaws and the alternatives

- 404.txt
Pasakosiu apie automobilio Smart perdarymą į elektromobilį. Kaip tai darėme prieš 10 metų ir kokios šiandienos realijos.
> Electric Smart, or fixing Mercedes's mistakes

- 404.txt
Glaustai pristatysiu, kas yra sąmoningumo meditacija ir pravesiu trumpą užsiėmimą naudojant dėmesio fokusavimo (angl. focused atention) techniką. Jei bus daugiau susidomėjusių, galėsiu pravesti kelis užsiėmimus skirtingais laikais, naudojant skirtingas technikas. Užsiėmimas vyks ne scenoje, o kokioje nors jaukesnėje vietoje (pvz. ant liepto), tad galite atsinešti ant ko patogiai atsisėsti.
(Goda)
> Sąmoningumo meditacijos (angl. mindfulness meditation) užsiėmimas

- 404.txt
Will look at the stars & Buck Moon.
> Changed workshop device

- 404.txt
Buvo užklausa iš bendruomenės, tai ruošiu pranešimą vakarui:
Pačiam teko išbnandyti įvairių programavimo kalbų ir matyti migracijų tarp jų,
tai pasidalinsiu savo patirtimi.
Iliustracijoms planuoju naudoti: PHP, Go, Rust, JavaScript, TypeScript, Scala.
Nebandysiu pasakyti, kuri kalba geresnė,
bet labiau kokiomis aplinkybėmis viena ar kita kalba pasirenkama dažniau
ir kaip sprendžiamos statinių ir dinaminių kalbų silpnosios ir stipriosios pusės.
Taip pat planuoju daugiau laiko palikti diskusijai/klausimams.
:arrow_right: Skaidrės: https://aurelijus.banelis.lt/prezentations/nta-2021/static-dynamic-typing.pdf
> Static vs Dynamic typing

- 404.txt
Per 10 dienu nukeliavau ~300 km. Tai buvo pirmas mano toks tripas, kuriam ruosdamasi informacijos ieskojau, zinoma, internete. Kazkas, ka radau interneto platybese, pasiteisino, kazkas ne. Vieni dazniausiai girdimu teiginiu/patarimu – kuprine turi sverti 10% kuno svorio, hike’inimui pasiruosi vaiksciodamas didelius atstumus, lazdos – tik vyresnio amziaus zmonems. Tiesa tai ar mitas? Siandien i siuos ir kitus klausimus galiu atsakyti ir patirties.
> Myths and truths about hiking gear: what I learned hiking 300 km in 10 days

- 404.txt
How to use camera settings, what are composition rules, what makes a good photo (useful for mobile's and diff. types of Camera's photography).
> Photography hacks for begginers to take better pictures.

- 404.txt
To get an official construction permit in a national park - sometimes you can, sometimes you cannot. Wat are criteria to check against in order to be sure that you are going to receive desired construction permit? This presentation provides key aspects and know-how gained on what to evaluate while looking at some land to buy in a national park, including the process on how to go there.
> Experience of buying a land for summerhouse in a national park

- 404.txt
Modern cars have heaps of ECUs talking with each other on various CAN buses. Messages on the bus are used to:
* report various telemetry
* turn on or off features
* configure devices like tire pressure monitors
I'll present on tools, projects and approaches used to extract even a tiny bit of this information from modern cars.
> Car CAN bus hacking

- 404.txt
DIY Apartment smart lock. My personal experience to: 
1. Design body and mechanical parts. 
2. Picking up best motor for project. 
3. Microcontroller
> DIY Apartment smart lock. Update 404.txt

- 404.txt
Best way to introduce your family to open source IoT computing - make…
… everything in Your home dependent on HomeAssistant!
I will tell you quite a funny but exciting story about making my new home smart. It will include interfacing (and, of course, literally burning out everything :D ) DALI lightning system which was the only thing that I had to get my hands dirty with code.
> Open-Source smart home with HomeAssistant

- 404.txt
In this presentation, I'll share a brief introduction to live coding, available tools and resources, share my experience making visuals for music festivals, and finish off with semi-interactive demo.
Tools I use for live coding – [orca](https://wiki.xxiivv.com/site/orca.html) and [TidalCycles](TidalCycles). On this presentation, I will mainly focus on live coding visuals with [Hydra](https://hydra.ojack.xyz/)
> Live coding visual performances

- 404.txt
Nostalgic trip down the memory lane, ~20 years back, when the Wireless was a little bit different beast and the dinosaurs had roamed the Ear...
anyways, this is a speech about particular generation of people who grown to be developers of various sorts, the technologies they (we) have used, communities they (we) have maintained and fun they (we) have had, while it lasted...
> Generation of W (Wireless Tech and Communities 20 yrs ago)

- 404.txt
will tell about:
- quick overview of hardware in Airplane models to feel what's like to construct one - quite easy! (Flight Controller "computer"`, e.g. [Mamba STM32 F405](https://ardupilot.org/plane/docs/common-mamba-basic-mk3.html) with onboard gyro/accelerometer/barometer sensors, control surfaces/Servos, motor(s), wing, radio systems for control/telemetry & video)
- [Ardupilot](https://ardupilot.org/plane/index.html) as the most popular and capable OSS autopilot software (not only for planes - quadcopters, cars, submarines,etc) including:
* main wing flight modes: airplane stabilization  (FBWA) and even autonomous flight missions - as programmed, or return to home (RTL) if lost control radio link
* VTOL - how  `Vertical Take-Off and Landing` simplifies and makes the takeoff safer, …
> Building autonomous Airplanes and VTOLs using Ardupilot

- 404.txt
I will bring cutting plotter and multiple colors of special film. You…
… will bring T-Shirt. We will cut any design on your T-Shirt.
Design can be one color only. I will bring like 6-7 different colors.
You can get cheap empty T-Shirts at pepco.lt or H&M.
You can print on existing old T_Shirt as well.
> T-Shirt workshop - cutting plotter for any design

- 404.txt
In short I wanna talk you through the basics of it and why it's such a great instrument to learn how to play
> Ukulele 101: Why it's such a great instrument

- 404.txt
Send Morse Code messages to your friends (and also receive, works both ways)
A workshop for kids to try out sending and receiving Morse Code messages.
There will be 4 Open Source DIY hardware kits with 3D printed Morse keys.
> Kids Workshop: Send Morse Code messages to your friends

- 404.txt
European Space Agency has the most extensive Earth monitoring programme called "Copernicus" in the World and provides a continuous flow of a few days frequency, open synthetic-aperture radar (SAR) and optical data [1] for 5 years already. Using data preprocessing pipeline [2, 3, 4] created under Horizon 2020 project combined with machine learning (ML) techniques and expert knowledge almost a real time monitoring with an extensive geographical coverage of crops [5], grassland mowing, forests, flooding with 10 m spatial resolution now is a plausible task.  I will present the basics of technology used, some working examples and main practical applications, services already used or tested by the State institutions. 
[1] https://scihub.copernicus.eu/dhus
[2] …
> ESA Sentinel data and ML for Earth monitoring

- 404.txt
- index.html
Papasakosiu apie savo išmaniųjų namų naujausius patobulinimus su ESPHome ir HomeAssistant:
- MH-Z19 - CO2 sensoriaus duomenų integracija į Home Assistant per ESPHome
- Flexit Nordic S4 rekuperatoriaus integracija į HomeAssistant'ą per HACS (Community Store)
- Flexit Nordic S4 rekuperacijos intensyvumo valdymas per HomeAssistant priklausomai nuo CO2 lygio kambariuose.
Bonus:
- Paaiškinsiu, kaip visa tai "paprastai" pasidaryti
- Papasakosiu apie nesėkmę su TV integracija su Google Home.
> Mano namų patobulinimai su ESPHome + HomeAssistant

- 404.txt
Jau nuo pat geležies amžiaus žmonės pradėjo gamintis iš įvairių metalų daigtus kurie jiem palengvintų gyvenimą, žmonems tobulėjant ir evoliucionuojant atsirado pinigai,papuošalai,buitį  menantys artefaktai ir kiti plačiai naudojami įvairių metalų ir paskirčių daigtai.
Paieškos metalo detektoriumi padeda aptikti ir rasti   žemėje -vandenyje  pamestus dalykus kuriu istorija gali siekti net du,du su puse tūkstančių metu istorija.
Niekada nežinai ką ir kur gali rasti,taciau būtent tas faktas ir žadina ieškotojo smalsumą ir vaizduotę.
> Lobių ir pamestų daiktų paieškos

- 404.txt
Half a year ago, I  became interested in underwater exploration, and decided to build an ROV (Remotely Operated underwater Vehicle). While there are commercial options available, the ones that fit my ultimate goal - reaching the deepest lake in Lithuania, Tauragnas (62.5 m) seemed priced quite unreasonably. So instead, I decided to tackle this challenge on my own, researching the complicated engineering required to build such an ROV from scratch with a minimal budget. There were many challenges to overcome - pressure proofing, building compact electronics, engineering thrusters and lights that can work submerged, routing electrical connections through watertight bulkheads, not to mention the software part - communication with topside via a thin tether, providing video feed, forwarding …
> Making underwater exploration drone (ROV)

- 404.txt
Papasakosiu kuo pavojingas mano senas hidroponikos robotas ir kokie rūpesčiai privertė kurti naują hidproponikos sistemą bei kaip sekėsi ją kurti. Juk kuriant naują sistema galima atsižvelgti į sukauptą patirtį ir nekartoti senų klaidų viską darant kažkaip "geriau". Na trumpai pasakius .. išėjo kaip visada. Antros sistemos efektas trenkė pagaliu: funkcionalumo poreikiai veržėsi per kraštus, o nauji bei anksčiau neišbandyti uždavinių sprendimų būdai atvėrė akis kiek daug galima klysti analoginiame pasaulyje. Sunku debuginti kodą kai mineralinių trašų prisotintas vanduo lieja kaimynus ;-)
> Gaminsiu augalų laistymo robotą, argi tai gali būti sunku ? 

- 404.txt
Ar žinote kas slepiasi vienkartinėje elektroninėje cigaretėje? Ar galit įsivaizduoti kaip man buvo pikta, kai jos viduje radau visavertę ir net iki pusės neiškrautą ličio jonų celę. O ar kam rūpi pingvinai? O kam rūpi kodėl Vilniuje taip dažnai dega šiukšlių konteineriai? Tai va man rūpi. Papasakosiu kaip antram gyvenimui įdarbinau atliekas. 
P.S. Renku nereikalingas elektronines cigaretes (atsivežkite tą pilną stalčių) gal kartu pavyks jas įdarbinti :)
> Žiedinė ekonomika arba kaip dariau akumų banką

- 404.txt
Kaip pasigamint CNC stakles naudojant brėžinius rastus internete, perkant detales iš ališkos ir ko galima pasimokint iš mano klaidų.
> Gaminau aš CNC stakles

- 404.txt
Šiemet universitete turėjom užduotį atkurti kažkokią dalį animacijos. Atliekant pastebėjom keletą detalių ir nesutapimų (kaip turėtų atrodyt 3D erdvėj), kurie pasirodė įdomūs. Rezultatas ir video, kurį aptarsiu https://youtu.be/btvu87FJ4AM
> Netikėti pastebėjimai perkuriant 2D animacija į 3D

- 404.txt
A basic rundown on why and how aerodynamics work. How lift and drag is created. Why you could care and the use cases.
I will also discuss some basics of Supersonic airflow.
With enough time (hopefully) for a Q&A afterwards.
> Aerodynamics for Dummies

- 404.txt
I will share my slow 10 years journey to achieve zero push notifications to my mobile devices.
> Zero push notifications

- 404.txt
Nelaikiau savęs benzingalviu, bet visi mano sprendimai renkantis automobilius tą parodo gan akivaizdžiai.
Į elektromobilius gan skeptiškai žiūrėjau, dėl mano akimis, komplikuotų ilgesnių kelionių. 
Tesla, tas gamintojas, kuriuo visi tiki, aš irgi tikėjau. Visada svajojau pasivėžinti su Tesla gaminiu. Ir štai vieną dieną pamačiau, kad Vilniuje atsirado Tesla nuoma. Jie turi ne šiaip sau kibiriukus, o Tesla Model Y "dual motor" "long range" su galimu nuvažiuoti kosminiu atstumu - 525 km. 
Nusprendžiau, kad reikia pabandyti! Pagaliau elektrinis automobilis, su kuriuo galėsiu nuvažiuoti pas tėvus į sodybą, Kauno rajone. ~130km nuo Vilniaus, tad drąsiai nuvažiuosiu, grįšiu ir net nereikės sukti galvos "kur pakrauti", kas mane labiausiai ir gąsdina.
Kaip manot, kaip sekėsi?
> Benzingalvis vs. Tesla: pirmieji nuotykiai

- 404.txt
The presentation will be about a 2D top-down evolutionary simulation[1] I made a year ago in Godot.
Each creature has a neural network, with time they adapt to the environment and become reasonably
smart where they avoid predators and find food and water.
I will show a couple of interesting simulations, some behavior which emerged,
and I'll go a bit into the details of neural networks.
[1]: https://github.com/LiquidFun/BoppieEvolution
> Boppies: Evolving "Intelligent" Creatures

- 404.txt
Vieną vakarą būnant "Drakono uodegos" tavernoje, tau "paukštelis" pakužda, kad vietinio miestelio - Farvestforto magų bokšto klerkas skubiai ieško keleto nuotykiautojų smulkiai užduočiai. Išvykstama rytoj vienai dienai. Žadamas geras atlygis ir reikalaujama diskretumo. Įdomu, kas tokio skubaus galėtų būti? Ir kodėl jie patys negali susitvarkyti su šia užduotimi? Į šiuos ir kitus klausimus bus atsakyta netrukus, su busimu klientu susitinki už dviejų valandų - vidurnaktį.
> Workshop: Shall we play a game? D&D pradedantiesiems

- 404.txt
Mentorius: **Kristina Orantaitė**
Per valandą pabandysiu perduoti Jums piešimo pagrindus išmoktus dailės mokykloj Utenoj iš gerbiamo mokytojo Repšio. Tikiuosi, kad po jų baltas lapas pradedantiems nebebus toks baisus.
Priemonės 12 žmonių bus (popierius, pieštukai, trintukai ir drožtukai).
> Workshop: Piešimo pagrindai (ką mokė dailės mokykloj)

- 404.txt
The web is not staying flat and it's time to start thinking in 3 dimensions. This presentation will introduce the basic theory of VR on the web and teach you how you too could start developing spatial experiences for web browsers and preparing for the metaverse.
> VR on the Web

- 404.txt
The wonders of doing random things on musical instruments and hopefully making it go nicely with other people doing other random things! I'll bring some instruments (mostly electric ones), share some basics and we'll try to create some grooves and vibes and jams and auditory goodniss and such. Prefferably more coherent than this text. No prior experience required!
> Workshop: Jam. The one with instruments. Musical ones

- 404.txt
Jau 10 metų organizuojame šį renginį!
Papasakosiu kaip ir kodėl :-)
> Intro: No Trolls Allowed x10

- 404.txt
Not a presentation, still fun though. Complete set for sim racing - Logitech G29 + handbrake + VR set. Free-time time attacks, drift attempts, rally tracks along with the tournaments that will be organized on Friday and Saturday (exact times and tables will be announced during the event)
> Activity: Racing simulator + VR

- 404.txt
- index.html
Meditacija apie tikrovę ir jos gamybą.
Nuo VR'o iki Bodriljaro: Platono ola, vyras liūto galva, propaganda, PR'as, sąmokslo teorijos ir tiesioginis veiksmas - tikrovės gamybos priemonių apžvalga ir refleksijos apie tai, kas ir kaip formuoja mūsų tikrovę. Kas yra tikrovės programavimo kalba?
> Praktiniai tikrovės formavimo aspektai

- 404.txt
I want to invite you to play with your kids some games based on psychological attachment theory (Attachment Play by Aletha Solter). Playing power-reversal, nonsense, separation and other attachement games will help with children’s behavioral and emotional challenges.
> Workshop for parents and kids: Attachement play

- 404.txt
Pasidalinsiu patirtimi kaip greitai ir kompaktiškai pasiekti internetą iš vietos, kur ne tik internetu net nekvepia, bet dažnai nebūna net ir paprasto mobilaus ryšio.
> Mobilus internetas miške

- 404.txt
After 5 years of using LiDARs commercially, I am still amazed at how awesome these devices are. I'll share some theory basics, some awesome facts and will finish with a live demo of what we look like to LiDARs in 3D. Disclaimer: tech talk, geeks only!
> How Stuff Works: LiDAR 101 + Live Demo

- 404.txt
Gaila, neturiu savo nicko githubo profilio.
> Zero push notifications - url fix

- 404.txt
Geru, sako reikia dalintis, tai noriu papasakoti apie įtraukiančią, smagią, fizinių galvosūkių veiklą. Į kurią įlindus gali ne tik super paprastai ir mažais resursais susiplanuoti įspūdingas atostogas, bet ir staiga pradėti domėtis fizika.
> Rock climbing. Kaip ir kur pasikabinti gyvenimą ant siūlo.

- 404.txt
DIY Coconut body scrub / Kokosų kūno šveitiklio gamyba.
> DIY Coconut body scrub / Kokosų kūno šveitiklio gamyba

- 404.txt
Would introduce basic massage technics, tips and tricks, and the most important thing how to do it safely and with pleasure.
> Massage workshop

- 404.txt
I am bringing four electric skateboards. Let's ride through the forest. No previous experience required. Tutorial and armour will be provided!
> Activity: Riding Electric Skateboards

- 404.txt
Pasakojimas apie patirtį kuriant įvairius matuoklius šiltnamiams, ankstesnes patirtis po protipų NTA, ir išsivysčiusią idėją, kurią norėtųsi išplatinti plačiau.
> Kvietimas prisidėti - patarti oro matuoklis kickstartinti

- 404.txt
Standartinis, bet labai laukiamas įžanginis pranešimas!
---
Jo metu išgirsite:
- Kiek ir kur galima triukšmauti
- Kur mesti šiukšles ir kur gauti joms skirtų maišų 4 free
- Kaip atskirti depozitinę tarą nuo prakąsto kotleto
- Kada valomi WC
- Kitą naudingą informaciją.
> Intro 2023

- 404.txt
How we got tired of writing boilerplate in C# and extended Roslyn, the C# compiler, with a bunch of custom features from other languages (like macros, implicits and custom records).
> Extending C# for fun and profit

- 404.txt
Most of us heard about image generation from text. Here I'll present an easy way to run it locally. Touch on some advanced stuff you can do with it (controlNet, LoRa, etc). I'm not deep in the field, so presentation will be layman to layman.
> Running image generation locally 101

- 404.txt
Will present state of the art lawn mowers that use RTK corrected GPS signals to get centimeter-grade accuracy.
Will be talking about making your own RTK station and following https://openmower.de/ project when constructing your own mower.
> Lawn mower robot

- 404.txt
will bring my microsoft flight simulator setup with VR glasses, rudder pedals & joystick for people to try out, so the experience will be rather similar to flying a real plane (will need space on table)
will explain the main formulas in aerodynamics for lift/drag (very simple math actually) and will explain what that means for airplane optimization, among them:
- what is the most efficient speed for specific plane to fly at? best `glide ratio = lift/drag (LDmax)`. how to measure it?
- basic optimization techniques when designing an airplane (how to choose good airfoil & wing shape if you know same of flight params, e.g. flying speed, weight, ...)
- formulas: lift & drag for airfoil, `lift induced drag` (approximation), total lift/drag for a wing
- propeller thrust is needed to compensate …
> PR170 Airplane aerodynamics 101 & flight simulator activity

- 404.txt
Nuo 2021-ųjų rugpjūčio 12 dienos išduodama Asmens Tapatybės Kortelė turi dvi programas: e-Paso ir elektroninio parašo. Svarbiausi skirtumai nuo ankstesnės kortelės, išdavinėtos nuo 2012-ųjų, yra: parašo sudarymo algoritmas, autentikacijos mechanizmas ir algoritmai, bei fizinė prieiga prie abiejų programų.
Pademonstruosiu kokie yra šie skirtumai, kas naujo, kas gero, kas nelabai, ką pavyko pataisyti ir ką dar galima būtų pataisyti.
> PR171: ATK 2021 kortelės programa ir jos funkcionalumai

- 404.txt
There is going to be a 5 seat soldering workshop and irons ranging from 10€ to 500€.
Around 20 soldering kits for kids and adults to have fun with electronics.
Workshop by @tovaldas and @kareiva
> Soldering workshop

- 404.txt
It became common to take digital photos with smartphones or bigger (DSLR) cameras and constantly scroll social media or e-commerce sites, assuming that "a picture is an exact representation of the reality." But is it always true (event without Deep fake)?
A talk from me (as [a photography enthusiast and software engineer](https://aurelijus.banelis.lt/)) will guide you through the journey of Digital photo evolution:
* Where we intentionally fake representation of the reality
* Why do engineers choose to do so
The talk should consist of:
* We had art, but we wanted digital sensors.
* We have basic sensors, but how does human perception work?
* The golden age of reality, but society wants more.
* The picture is static, but the user experience is not (JPG → WEBP → AVIF)
We were looking to the …
> PR174 Digital photos: How much reality is left there

- 404.txt
Ladies and Gentlemen, imagine for a moment, the world of a sniper or a precision shooter. It is a realm that seamlessly fuses art and science, with an absolute need for accuracy. This precision hinges on an impressive wealth of data; the ballistics of each round, the fluctuating dance of weather conditions and atmospheric density, the unyielding pull of gravity, the intimate knowledge of their firearm's quality, the subtle influence of spin drift effects, the whispered secrets of the wind, and even the subtlest touch of the Coriolis effect. Quite an overwhelming list, isn't it? So, the intriguing question that naturally arises is - how do these sharpshooters manage to juggle all of these elements and yet hit their mark with such astounding precision? Let's delve into this fascinating …
> Sniper precision shooting for nerds

- 404.txt
Pristatyme kalbėsiu apie tai kokias teises į kūrinį turi autorius ir apie šių teisių apsaugą.
Ar kada nors susimastėte kodėl robotas nėra laikomas kūrinio autoriumi? O gal smalsu kokias teises įgyjate padarę nuotrauką ar nutapę paveisklą? Kaip tomis teisėmis pasinaudoti? Savo pranešime papasakosiu kas yra intelektinė nuosavybė, kokios teisės atsiranda sukūrus kūrinį, kaip jas tinkamai perduoti ir apsaugoti. Pakalbėsime ir apie tai kaip nepažeisti kito asmens teisių.  
Pasakos Lukas Valentukevičius, intelektinės nuosavybės teisės specialistas
> Teisės į intelektinę nuosavybę, kodėl robotas negali būti autorius

- 404.txt
Pavadinimas kaip ir viską paaiškina. Marukas papasakos su kokiais įnagiais tekdavo muzikuoti, kai pasirinkimas ir priėjimas nebuvo toks, kokį turime dabar.
> Elektroniniai muzikos instrumentai 90-ųjų DIY scenoje

- 404.txt
Sveiki, man kilo mintis camp'e pastatyti/pakabinti lentyną (tikiuos rasiu kampelį pavėsinėje) senoms su IT susijusioms knygoms (paskaityti renginio metu, ne išsinešti!). Turiu tokių nemažai ir būtų smagu, kad kas tokių turite atsineštumėte irgi į bendrą fondą 😄
> Attraction: Bookshelf of old IT-related books

- 404.txt
Rubiko kubiko istorija ir pasaulio rekordai. Rubiko kubiko algoritmai ir įdomūs faktai apie rubiką kubiką.
Kalbės mano sūnus 13m
> Rubikas kubikas

- 404.txt
I recently plunged into the world of scuba diving and let me tell you - it's like discovering a whole new world that's waiting to be explored. It turned out to be somewhat more technical than one might anticipate, yet remains remarkably accessible to anyone, irrespective of age. I will give a practical run-down of how it works and how you can kick off your own underwater adventure:
- Diver certification and the associated legalities
- Everything you need to know about the equipment (along with some demo stuff)
- Getting your feet wet without breaking the bank
- Making it official and becoming a certified diver
- What's next? Fun stuff you can do once you're certified.
> Scuba Diving 101: Practical Intro into Underwater Exploration

- 404.txt
A demo-heavy introduction to Logisim (a circuit simulation software) and my first CPU I designed in it.
A high-level overview of what it takes to design an ISA and implement a CPU. You will learn:
* The insides of how a fully-functional (yet very minimalistic) CPU works
* What are the prerequisites to do it on your own
* Which bits are easy and which are challenging
* What are reasonable next steps
> Design Your Own ISA and Build a (Virtual) CPU

- 404.txt
Žygyje su vaikais suaugusieji dažniausiai turi (ir neretai nori) būti cool dude'ai, kurie visada žino, ką daryti, ir kuriems viskas lengva, tačiau tai daugeliu atvejų priklauso nuo, kiek pastangų įdėta į planavimą. Planuoju pakalbėti, kodėl ir kaip reikėtų organizuoti žygį ir stovyklavimą su 4-14 metų vaikais Lietuvos gamtoje, kad (planas minimum) grįžtumėte gyvi irba (planas maksimum) patenkinti: apie ką reikėtų pagalvoti planuojant logistiką, maitinimą, veiklas. Remsiuosi asmenine žygiavimo su savais ir skolintais vaikais praktika ir skautavimo patirtimi.
> Hiking and camping with kids: survival guide for adults

- 404.txt
Same as last year I will be bringing a bunch of electric skateboards and protective gear. People of all skill levels/ages are welcome to try. I will be teaching the riding technique as well as sharing info on building your own.  
Apart from that I was imagining a race for those who already are experienced.
> Electric skateboarding workshop

- 404.txt
My presentation explores the captivating world of mini sumo robots. These compact machines fuse strategy and skills of various degrees: mechanical, electrical engineering, and programming. I'll discuss construction challenges and ongoing obstacles in optimizing their performance. By showcasing the art of sumo and the strategies I use, I aim to inspire an appreciation for the mini sumo robots.
> The Art of Mini Sumo: Strategy and Skill

- 404.txt
Su muzika susidūrę esame kiekvienas, tačiau retas pagalvojame, kiek make'inimo idėjų galime joje pritaikyti. Pranešimas, skirtas kiekvienam, o labiausiai - visiškai "žaliam" muzikoje, galbūt svarstančiam, ar apskritai verta bandyt į ją įmerkt kojas. Pranešime atskleisiu: kaip sužinoti, ar turiu klausą? Kokius patarimus duočiau besimokančiam muzikuoti? Bei nukelsiu paslapties šydą atskleisdama "nematomas" muzikantų paslaptis, pavyzdžiui, kaip akordeonistai žino, kurį iš dešimčių vienodų mygtukų paspausti?:) Tikiuosi, jog po pranešimo muzika nebeatrodys tokia paslaptis, ir susidomėjusius muzikavimu mielai pakonsultuosiu ir toliau.
> How to music 101

- 404.txt
Nuotolinė vaiduoklių gaudymo priemonė, kaip iš RC mašinos pavyko padaryt vaiduoklių gaudyklę kuri atrodo 'visai kaip iš naujausio filmo'. BYOG - bring your own ghosts.
> Ghostbusters R.T.V - cosplay inžineriškai

- 404.txt
Workshopo metu susikonstruosite robotuką, kuris valdomas bluetooth'u per telefoną (android) ir su šiuo robotuku labai norint bus galima sudalyvauti ir sezono metu vykstančiose varžybose. 
https://imgur.com/a/4znTDii
Taip pat, po workshopo padarysime mini varžybas su smulkiais prizais ir apdovanojimais
https://forms.gle/ZVFTUGhQUseud5fdA
Šiuo metu yra užsiregistravę 11 žmonių, o iš viso bus 20 komplektų. Žmonės kurie neužsiregistruos, nebus garantuoti, kad galės susikonstruoti robotuką. Taip pat 1 robotukas kainuos 12 eur.
> Antweight combat robot workshop

- 404.txt
In my presentation on antweight combat robots, I will try to showcase these 200g machines that engage in battles within a small arena. I'll discuss the challenges I faced while building them and the ongoing issues I still encounter. Despite their size, these robots require quite intricate designs. Through my presentation, I aim to demonstrate the creativity and problem-solving skills involved in bringing these antweight combat robots to life.
> Antweight presentation: Small Bots, Big Battles

- 404.txt
Last summer I built the first iteration of the underwater exploration drone (ROV), which was presented in the previous NTA. Although it allowed to perform several expeditions, I soon discovered it's limitations and design flaws. I spent the next year building the second generation ROV that addresses these issues. It was a fun and educating challenge with lots of new obstacles to overcome. The new ROV features a far more robust frame, full 6-axis control, extended sensors - compass, depth, temperature, gyroscopes and accelerometers, allowing for far better navigation and research. In addition, ROV now features a gripper, dedicated controller with video feed and telemetry, is now rated to 100 meters (still limited to 62 m. - the deepest lake in Lithuania), and is now very close in it's …
> Home-made second generation ROV

- 404.txt
During the last decade AI was used to automate simple repetitive tasks (e.g. dog vs cat). However, more options are available to automate intellectual tasks. I have been involved in AI research & consultations for the last 10 years mainly in finance & logistics. I will give a talk of how to think about AI application for expert work automation related to financial decisions – valuation, pricing, etc. The content of the talk:
1.	Project Experience
2.	Intro to AI & Algorithms
3.	Intro to simulations & agent-based modelling
4.	Thinking about data-driven products
5.	How to start implementation?
6.	Q&A
> Automating financial decisions with AI

- 404.txt
Trumpa apžvalga Lietuvą "sudrebinusių" (arba veikiau nutikusių) data-leak'ų. Koncentruojantis labiau ties turiniu bei pastarųjų poveikiu (arba veikiau poveikio trūkumu).
Prabėgsiu pro, savo nuožiūra, įdomesnius, ir atvirame internete cirkuliuojiuočius data-set'us. Kurie, mano nuožiūra, turėjo susilaukti daugiau dėmesio. Tačiau... nugeso ir užsimiršo.
Think of CityBee and Filmai.in.
> Besikapstant po skaitmenines nuotekas

- 404.txt
Kepsime šakočius. Visi norintys išmėginti ir prisidėti prie šakočių kepimo - maloniai kviečiami. Iškeptus šakočius dalinsimės visi kartu prie arbatos/kavos/kt.
Procesas, įranga ir idėjos "statyti" nuo visiško nulio, pasitelkiant pramoninį špionažą, kitą nelegalią veiklą bei pažintis.
> Šakočių kepimas

- 404.txt
Atsinešiu kelias  sadhu lentutes pačio padarytas naudojant lazerį fanera ir žinoma vinis. Pasidalinsiu brėžiniais jeigu norėsi pasidaryti savo. Bus galima pabandyti pastovėti (20 min). Skaudės bet tu gali pergalėti save, nes ir aš galėjau.
> Atsinešiu kelias  sadhu lentutes kad galėtumės ant jų pastovėti

- 404.txt
Origami (popieriaus lankstinių) dirbtuvės.
Atsinešiu origami popieriaus ir atsispausdinsiu įvairaus sudėtingumo origami modelių diagramų. Ras ką veikti tiek vaikai, tiek suaugę :)
> Origami dirbtuvės

- 404.txt
Pasidalinčiau asmenine patirtimi kokius respiratorius naudoju suvirinimo, metalo, smėliavimo ir kitiems darbams, kuo jie pasiteisino ir kuo ne. Filtrų klasės, PAPR sistemos. Taip pat galimybe pagerinti turimą respiratoriu. Could maybe do it in English.
> Oro filtravimas asmeninei ir kolektyvinei darbų saugai

- 404.txt
Turėjome elektros rinkos liberalizacijos procesą. Kuris įvyko labai netinkamu metu - energetinio karo metu. Kainos šoktelėjo sparčiai. Tačiau Lietuva yra šalis, kurioje galima rasti lankstumo ir greičio. Noriu pasidalinti savo įspūdžiais analizuojant asmeninius elektros vartojimo įpročius ir kaip pritaikius maker'io įgūdžius bei planavimą pavyko sumažinti elektros sąskaitą perpus.
> Įspūdžiai, sprendimai bandant sumažinti elektros sąskaitą

- 404.txt
In a world filled with dragons, demons and many other creatures, adventures happen to those who seek them. Quests posted by kings, queens and peasants alike await brave souls to fill them. A group of such brave adventurers has just finished a quest. On their way back, before reaching the city, they decided to set up camp and figure out What actually happened? 
This is a LARP (Live Action Role Play). No previous experience is necessary to participate as long as you're eager to take on a role and improvise. No preparation is needed either. The game will start in the evening after the presentations. It will take at least 3 hours. Bring snacks and drinks to share with your adventuring partners.
> Activity: LARP "What Actually Happened?"

- 404.txt
Severely overengineering and overcomplicating differential steering gearbox
Kalbėsiu apie tai, kaip suprojektavau ir sugalvojau padaryti per daug sudėtingą pavarų dėžę skirtą vikšrinei transporto priemonei.
> Severely overengineering differential steering gearbox

- 404.txt
- Pasidalinsiu įdomybėm apie bičių gyvenimą, hierarchiją, motinėlių santykius
- Papasakosiu, kodėl be bičių pasaulis būtų liūdnas ir alkanas. 
- Papasakosiu apie savo pažintį su bitėmis, pirmuosius avilius (tiek mano, tiek pasaulyje), ir kaip sekasi dabar.
> Paslaptingas bičių pasaulis: šeima, darbai, įdomybės

- 404.txt
Sveiki,
Tikiuosi viską teisingai registruoju :) . 
Manvydas iš KMS pirmą kartą vyksiu į 404 camp.
Pristatinėsiu savo bandymus pagaminti mažus epoksido papuošalus ir kaip restauravau seną slėgio indą šiai paskirčiai.
Prašau leisti pristatinėti savaitgalį arba vėlai penktadienį.
Gaminių nuotraukos instagrame bloom_green_boom.
> Small epoxy jewelry project including restoring pressure pot

- 404.txt
- Duomenys, kuriuos keliam į internetą.
- Skaitmeniniai (ir ne tik) produktai, kuriuos įsigijom.
- Paslaugos, kurias naudojam.
Visa tai gali bet kada pradingti. Kiek tikėtina, kad tai nutiks ir kokios galimos priežastys?
> Kodėl man trukčioja akis perkant el. knygas amazonėje?

- 404.txt
Asmeniniai atradimai apie atmintį ir mokymąsį, klaidos ir pamokos.
Prieš maždaug 3-4 metus supratau, kad nemoku tinkamai mokytis, tam kartui išmokstu ir po kurio laiko žinios "išgaruoja". 
Tai inspiravo pradėti domėtis kodėl taip vyskta, kaip galėčiau išlaikyti žinias.
Pradėjau savo kelionę mokytis mokytis, per tą laiką perskaičiau daugybę mokslinių straipsnių, knygų apie atmintį ir mokymąsi. Per tą laiką išbandžiau praktiškai perskaitytus dalykus, visokias technikas, todėl galiu pasidalinti patirtimi kas veikia, ką išmokau ir kokias klaidas dariau.
Papasakosiu:
🔷kaip veikia atmintis (trumpalaikė ir ilgalaikė),
🔷kuo svarbus miegas,
🔷kaip reiktų efektyviai mokytis, nesvarbu ką (technikos ir metodai), 
🔷kokių klaidų reiktų vengti.
> Asmeniniai atradimai apie atmintį ir mokymąsį, klaidos & pamokos

- 404.txt
I would give a presentation on my experience creating a programming language as a fun side project and also how one can do the same. 
Outline:
- intro on programming languages
- core concepts, components of a compiler
- pitfalls I encountered making my own language
- materials for learning more
> An amateurs guide on how to make your own programming language

- 404.txt
Did you ever want to dive to an ocean, sea or so and see what's under, but without all the bulky gear that keeps us alive by providing oxygen? Just get goggles and here we go! Sounds simple!
There is such a cruel sport, or leisure activity, depending on how you see the world, called "apnea diving". That is, to plain Lithuanian, "diving without supplemental oxygen". In this talk I will go through:
- some apnea diving trivia.
- how a human body reacts to lack of O₂ and too much CO₂.
- how much can be pushed it before it's not safe?
- how to get started?
I will bring equipment and do some on-the-spot tests that prove the theories with a volunteer or two.
> Apnea diving 101

- 404.txt
The Quiet Year - pats keisčiausias praeitų metų mano sutiktas žaidimas. Daugiau info - [https://buriedwithoutceremony.com/the-quiet-year](https://buriedwithoutceremony.com/the-quiet-year). Noriu pasidalinti ir pravesti 2-3 valandu sesija 3-4 zmonėms. Kind of RPG, bet character nereikia turėt :)
> Workshop: The Quiet Year - map-buildin/rpg/storry-telling

- 404.txt
I will briefly talk about the science behind the oscilloscope music and present few clips.
Preferably it would be good to do it in the evening with the sound on.
> [2023] Show and tell: oscilloscope music

- 404.txt
Sea shanties domiuosiu jau kūrį laiką, giliau pradėjau domėtis ~2018. 
Papasakosiu apie jūrinkų dainų istoriją ir paskirtį laive. Aptarsiu skirtingus tipus, kas organizavo. Taip pat įvairių įdomių faktų. Jei bus norinčių bus galima ir padainuoti. Įspėju prastai dainuoju :)
> Sea Shanties: Istorija & Trivia

- 404.txt
During Covid demand for grocery delivery services spiked. A lot of people were manually refreshing page to get an open spot to order groceries at barbora.lt. I created an alert tool that informed about available slots. The most intriguing part was that the tool received contributions from multiple developers who added support for multiple operating platforms. This talk will mostly focus on social aspects of the open source project but will also add some technical details about creation of the alert tool.
https://github.com/aidiss/barbora-delivery-spot-alert
> Personal Story of Partly Succesfull Open-Source Side Project

- 404.txt
Esu paprastas žmogus, kompiuteristas, didžiąją laiko dalį praleidžiu sėdėdamas.  Laisvalaikiu minu dviratį mėgėjiškai. 
Šiomis dienomis įveikiau 300km vienu važiavimu.
Norėčiau pasidalinti šviežiais įspūdžiais apie savo kelionę:
- Pasiruošimas
- Važiavimas
- Atsistatymas
- Ką daryčiau kitaip?
> 300 km dviračiu vienu užsėdimu

- 404.txt
Writing toy compiler by hand using golang. 
Goal is to produce as small binary as possible for use in very limited MCUs. No lexer or parser library is used.
> Compiler from scratch

- 404.txt
Get ready to have a mind-blowing conversation with a humble old gaming PC. Strap on a headset and let the magic unfold as you talk to the box about your projects, your life, and everything in between.
Well...actually it's just an experiment of what an old gaming PC can run in offline mode.
Ingredients:
1. An old PC with a second hand Nvidia RTX 3060.
2. A Jabra headset.
3. An offline AI:
* Llama-2 large language model (7B)
* Whisper (large-v2) for speech to text
* Piper for text to speech
4. A bit of Python code.
> Workshop: AI in a box

- 404.txt
Norėjau dukrai tik ką grįžusiai iš JAV, dalyvusiai ten didžiausiuose chorų festivaliuosi leisti kalbėti, bet galiu pasidalinti pasižaidimų su Wii patirtimi.
> Nintendo Wii gidas. Konsolės taikymas mokant vaikus skaityti

- 404.txt
- index.html
Pristatys: Dmitrij/VEC7OR
Noriu papasakot istorija kaip as kuriau specialius sviestuvus kurie leidzia pamatyt pasauli akimus zmonius kurie nemato spalvu ir pasidalint patirtim ir problemom su kuriuom susiduriau kelyje.
> Daltonizmo emuliatorius 

- 404.txt
Arnas papasakos kaip padaryt iš senos radijos bluetooth kolonėlę tiem kas tokių turi ir ateity norėtų suteikti joms antrą gyvenimą,
Nuo Annos: Arnas yra dvyliktokas kuris apsilankęs anais metais gavo tiek įspūdžių ir įkvėpimo kažką padaryt pats, kad šiemet grįžta su prezentacija.
> Retro Bluetooth kolonėlė

- 404.txt
Smiltė will lead a workshop in which we will be creating 2d and icosahedron paper models and stickers of planets / spaceships / aliens / etc what will come to our mind. Also there will be face painting session with planets and stars. Inspired by stickers workshop which was held in NTA 2021.
> The cosmic workshop for kids

- 404.txt
Paaiškinsiu jums viską nuo kas yra vizualus efektas iki ko reikia kad juos galėtum daryti pats. Parodysiu savo sukurtus projektus kaip pavyzdžius ir pamokysiu kaip jūs galite sukurti juos be jokio biudžeto.
> Vizualūs Efektai Pradedantiesiems

- 404.txt
Karas Ukrainoje sudėtingiausias ir technologiškai pažangiausias karas žmonijos istorijoje, kur abi pusės rodo ypatinga inovatoriškumą ir greitį technologijų srityje, kad pasiekti pergalių. Esu bepiločių orlaivių inžinierius-operatorius. Pasidalinsiu nedidele patirtimi iš fronto ir įžvalgomis apie tai kaip technologijos atneša pergales.
> Topic: Technologijų karas

- 404.txt
Pernai metais dalyvavau labai geram No Trolls Allowed aka Camp Not Found 404 hackercampe. Ne pirmą kartą teko padėti žmonėms pakabinti jų tentus ar tiesiog rišti virves prie medžių. Kilo mintis, kad būtų verta visiems norintiems papasakoti kaip ir kodėl aš naudoju tentus. Ir kodėl tentą laikau vienu universaliausių stovyklavimo įrankiu.
Apžvelgsime:
- Kas tas tentas?
- Kaip jį naudoti?
- Kaip išsirinkti?
- Kiek kainuoja?
- Galėsim surengti mažas dirbtuves, kurių metu išmokinsiu kaip pasikabinti tentą.
> Kodėl tentas yra geriausias stovyklautojo įrankis

- 404.txt
Pastaruosius kelis metus vykstantis elektronikos ir litavimo kampelis.
Pilnas planas:
https://docs.google.com/spreadsheets/d/1ojnfhCKnoLtNbkt7WMjyCz2VRLGk4mv2kjon3CYcydA/edit#gid=0
> Litavimo ir elektronikos dirbtuvės visiems

- 404.txt
Making sure transparency is famous and visible.
> Be more transparent about fame

- 404.txt
Sodyba nuo nulio (2020 NTA istorijos tęsinys)
Beveik 5 metai įgyvendinimui - tokia reali trukmė sodybai nuo nulio iki galimybės nakvoti ir turėti visus patogumus kažkur toli gamtoje. Sudėtinga? Brangu? Sėkmės, nesekmės? Ar tai jau visų "vargų" pabaiga? Ar tai dar kartą kartotumėme? Kodėl taip ilgai? Pristatymo metu kalbėsime apie faktus - kaip? kas? kodėl? kiek? Pristatymo tikslas - supažindinti dalyvį su faktais, kurie leistų nuspręsti ar verta leistis į sodybos statybos procesą, ar visgi geriau ieškoti tokios, kuri jau pastatyta. Ir mes turime argumentuotą atsakymą!
> Sodyba nuo nulio (2020 NTA istorijos tęsinys)

- 404.txt
Šiais metais įrengsime dedikuotą zoną, skirta bendram maisto ruošimui. Šią vietą vadinsime "virtuve". Ją planuojame įrengti prie didžiojo liepto (ten kur pernai buvo kepami šakočiai).
Virtuvėje rasite:
- Paviljoną, skirtą apsaugoti nuo oro išdaigų.
- Elektrą ir apšvietimą.
- Didelį stalą, o gal net kelis.
- Keletą suolų.
- Šiukšlių maišų, gal kažkiek popierinių ranšluosčių.
- Netoliese esančią laužavietę ir grilį, bei malkų.
- Kažką, ką atsineš renginio dalyviai.
Virtuvėje nerasite: maisto, gėrimų, įrankių, bei kitų rakandų. Viską atsivežkite patys.
Mes norime, kad gamintumėte maistą kartu. Ir tikimės, jog taip bus lengviau rasti pagalbininkų bendrų patiekalų gamybai. Jei planuojate kažką gaminti ir planuojate dalintis su kitais - kviečiame maistą gaminti bendroje virtuvėje! Nepamirškite …
> Bendra maisto ruošimo zona

- 404.txt
Reflections based on explaining the speed of the internet, as well as some intricacies of PHP, to the engineers that are more comfortable with C++ and abundance of very fast hardware.
A talk that has very little in terms of applicability, but might elicit some light chuckles.
Practical outline:
- Based on my more recent work with C++ engineers who use very sophisticated system, who are integrating with 3rd party service providers (running regular web applications).
- What it takes to explain to those engineers how the regular web applications function: what to expect in terms of an average response time, how the typical web system interacts with data stores, what is the capacity of the average system to observe their own performance and dig into the details. 
- I will share reasons and …
> Kaip pasakojau inžinieriams apie internetą ir PHP

- 404.txt
An overview of the state of the art for open and affordable silicon designs.
* A siloed and paywalled traditional world of silicon design
* New open source developments
* The price, and the ways to reduce it
* My Tiny Tapeout project: Collatz number cruncher
> Building Your Own Chips Is Finally Affordable

- 404.txt
Hipių festivalis geek'o akimis. Ko galima pasimokyti iš anti-technologinio festivalio, kaip jo idėjos artimos NoTrollsAllowed arba Atviro kodo bendruomenėms.
Aš įprastai nepraleidžiu NoTrollsAllowed festivalio, bebent yra Covid'as, medaus kelionė, ar... draugai įkalba važiuoti iki Europinio `Rainbow Gathering` Bulgarijoje (2022). Todėl, manau, simboliška yra papasakoti apie hipių susitikimo fenomeną.
Pranešimo metu planuoju:
* Pristatyti, iš kur kilęs `Rainbow Gathering`
* Kaip ir kodėl veikia anti-technologinis "mini miestelis":
* Be mikrofonų, be telefonų, be elektros – per kilometrus sukomunikuoja
* Be laikrodių, be prižiūrėtojų – dalinimasis žiniomis ir dirbtuvės (kuo tai bendra su NoTrollsAllowed)
* Be pinigų, be vieno vadovo, nelegaliai – dalykai nesugriūna
* Be policijos, ar …
> Rainbow gathering

- 404.txt
Atsivešiu įvairių su mechanika susijusių dalykų - metalinių konstruktorių, vadovėlių, automobilių detalių išpjovų. Panašiai, kaip praeitais metais, tiktai su truputį papildyta kolekcija. Taikau į vaikų užimtumą, bet turėsiu keletą dalykų, kurie bus įdomūs ir tėčiams/mamoms.
> PR249 Tepaluotųjų pirščiukų kampelis

- 404.txt
Although we are not often able to put the sense in words, in a work-related environment, the interpersonal dynamics work differently depending on with whom and why we join the efforts. In this presentation, Il'd like to look closer at what are the differences between teams and groups and challenges related to decision making in such environments. Inspired by workplace transition from small company to small enterprise.
> Groups vs teams: differences in decision making process

- 404.txt
For many years I had frustration - processing quite some information I wanted to keep the most resonating principles, ideas, things where I wanted to dive deep, and snippets of my thoughts.  
I would happily jump on the newest shiniest app in the market for notes/knowledge just to find myself with a pile of disorganized information and a desire to start all over with a new shiny tool. 
All of this, until I found a new tool to do it which has completely changed everything and became a multiplier for my brain. 🧠
Knowing my experience with the shiny tools I was still afraid of the honeymoon effect and hesitant to recommend it 😅 but 2 years after using it I'm sure this is something I wish I had 10+ years ago. 
Here is one of my knowledge graphs:
I'd like to share how I manage my knowledge …
> My approach to Personal Knowledge Management (PKM)

- 404.txt
I recently plunged into the world of scuba diving and let me tell you - it's like discovering a whole new world that's waiting to be explored. It turned out to be somewhat more technical than one might anticipate, yet remains remarkably accessible to anyone, irrespective of age. I will give a practical run-down of how it works and how you can kick off your own underwater adventure:
- Diver certification and the associated legalities
- Everything you need to know about the equipment (along with some demo stuff)
- Getting your feet wet without breaking the bank
- Making it official and becoming a certified diver
- What's next? Fun stuff you can do once you're certified.
> Scuba Diving 101: Practical Intro to Underwater Exploration

- 404.txt
A follow up to last years #169 talk where I talked about building an [OpenMower](https://openmower.de/).
Now I have been using OpenMower for a season and I will talk about:
* building monitoring stack for the OpenMower
* troubleshooting GPS and WiFi connection issues
* new features of OpenMower that have been added since
* new tools that have been created in the OpenMower ecosystem
https://github.com/ntacamp/404.notrollsallowed.com/assets/422086/c7a71536-7462-4991-a871-c028a6771b9f
> Using autonomous 2cm precision GPS lawnmower for a year

- 404.txt
How I made an android radio for my first car out of an old phone, salvaged amplifier and Arduino.
> Android Auto headunit from scratch

- 404.txt
Movies about hackers has scene when intruder picks the lock to get into the property. I was curious - how hard could it be? Let’s find out together;)
I’ll bring two sets of lock picking tools, some practice locks. If you have your own tools, locks - please bring to the camp and come to workshop.
Disclaimer. I’m really terrible at this, but I hope people with patience with enjoy;)
> Lock picking workshop

- 404.txt
Remiantis asmenine patirtim, papasakosiu kaip DBT (Dialectical behavior therapy) padėjo man valdyti įtampą ir jausmus, su pavyzdžiais ir patarimais.
> Kaip man DBT padėjo valdyti įtampą ir jausmus

- 404.txt
Crokinole: kanadietiškas kerlingo ir biliardo hibridas. Apsimokysim, o gal ir mini čempionatą surengsim. Daugiau info - https://www.youtube.com/watch?v=XMKzeg78peg
> Crokinole: learn to play workshop

- 404.txt
Alų pasigaminti nėra sunku, net aš sugebėjau :D, tai kodėl ir kitiems nepandžius?
Papasakosiu apie skirtingus gamybos būdus ir kaip skiriasi jų procesai. Taip pat aptarsiu įrangą, kuri reikalinga pasigaminti alaus namie.
Kol supplies bus, galima pasimėgauti alumi.
> Beer making 101 + tasting

- 404.txt
Papasakosiu apie tai kuom įpatinga (ir kuom nelabai) Aviacinio mechaniko darbas, Ryanair'a iš to ką pastebėjau iš vidaus po 2 metų darbo. 
Atsakysių į klausimus kurie jus domina apie Ryanaira, ir Avaicija aplamai (kiek sugebėsiu bent)
> Esu Mechanikas pas Ryanair'a, Avia mech darbo specifika +QA

- 404.txt
Per dirbtuves keliais būdais pinsime iš virvių raktų pakabukus.
Viską turėsime tik nepamirškite iš namų pasiimti gerą nuotaiką! 😉
> Raktų pakabukų pynimo dirbtuvės

- 404.txt
- index.html
Papasakosiu apie mėgėjišką radiją, ką galima nuveikti ir nuo ko pradėti. Campe tradiciškai (galimai) veiks Vilniaus universiteto radijo klubo stotis, tad bus proga pabandyti užmegzti ryšį eteryje.
> Kas yra mėgėjiškas radijas?

- 404.txt
Bus ištiestas tinklas, paklotos linijos, padėta skraidukų su raketėmis.Galėsiu papasakoti taisykles, pamokyti, kaip taisyklingai smūgiuoti, laikyti raketę
> Badmintono pasižaidimai

- 404.txt
Blizgučių stotelėje ir maži, ir dideli galės būti papuošti glitter’iu ir laikinomis tattoo fainiausiam vasaros camp’ui!
> Workshop: Blizgučių stotelė

- 404.txt
Papasakosiu
* Kokį teigiamą poveikį šis sportas turi sveikatai: akim, nugarai ir didelei daliai įvairių raumenų.
* Kodėl tai yra "meditacinis" sportas.
* Kur tai galima daryti Lietuvoje.
* Ir kiek tai maždaug kainuoja.
* Esant tinkamom oro sąlygom galėsime išbandyti.
> Burlentės - puikus sportas programuotojams

- 404.txt
Šiame pranešime papasakosiu, kodėl pėdų ir kojų nagų priežiūra yra svarbi vyrų sveikatai ir higienai. Apžvelgsiu dažniausias pėdų problemas, jų priežastis, pasekmės ir prevencijos būdus. Taip pat papasakosiu apie teisingą avalynės pasirinkimą, nagų kirpimo techniką ir pėdų priežiūrą namuose.  Papasakosiu kada kreiptis į pedikiūro meistrus ar podologus, ir kokias procedūras jie atlieka. Dėmesys bus skiriamas ir vyrų pedikiūro ypatumams bei stereotipų griovimui, parodant, kaip pėdų priežiūra gali pagerinti gyvenimo kokybę ir sveikatą.
> Vyrai ir pedikiūras: kodėl verta rūpintis savo pėdomis

- 404.txt
Pristatysiu savo DIY projektą: 
Savadarbė nešiojama oro filtravimo sistema, skirta apsaugoti kvėpavimo takus ir veidą nuo fizinių pavojų dirbant dirbtuvėse. Keičiamas filtras, 3d spausdintos detalės, nardymo kaukė ir kt.
> DIY PAPR oro filtravimo sistema

- 404.txt
Nedarysiu atskiros paskaitos, bet atsivešiu šiemet susimeistrautą edukacinį aviliuką (1 rėmo aviliukas su stiklinėm sienelėm), kur bus galima saugiai apžiūrėt dirbančias ir savo natūralioj aplinkoj gyvenančias bites, pačiupinėt bitinko įrankius, apsirengt kostiumą. Galvoju skirti kelis laikus kai visiems atėjusiems (tiek vaikams tiek suaugusiems) papasakosiu apie bičių gyvenimą ir jų stebuklus.
> PR274 Edukacija apie bites

- 404.txt
Rytinė mankšta su Lotynų Amerikos ritmais
Veda Austėja & Božena
Paturbinta rytinė mankšta su Zumbos prieskoniais. Zumba – tai energingas ir smagus fitneso užsiėmimas, derinantis šokį ir aerobikos judesius pagal užkrečiančią Lotynų Amerikos muziką. 
Pačios mėgstame retkarčiais nueiti į tokias treniruotes ir išsikrauti, pasisemti pozityvo. Tad tą pasiūlysim ir jums – energingus, galvą pravėdinančius šokius su neprofesionaliom trenerėm.
> Rytinė mankšta su Lotynų Amerikos ritmai

- 404.txt
Pasakosiu apie tai, kaip naudojant lazerius ir medžiagas su ląstelėmis galima atspausdinti darinius, kurie atlieka žmogaus organų funkcijas. Aš su tuo susijęs tuo, kad startuolis, kuriame dirbu software engineering leadu, užsiima tokios technologijos vystymu. Manau, kad paklausyti įdomu, nes tai yra vienas iš (trendy buzzword) "deep tech" pavyzdžių.
> Kaip atspausdinti inkstą?

- 404.txt
Pristatymas dr. Lisa Damour knygos "Untangled: Guiding Teenage Girls Through the Seven Transitions into Adulthood" pagrindu.
https://www.goodreads.com/book/show/25614847-untangled
> Suprasti paauglę: septynios pakopos į suaugusiųjų gyvenimą

- 404.txt
Padarysiu maistelio kokius tris puodus po 20 L. Tikėtina sriuba, troškiniai ar košės. Laikas parodys.
> Kornukopija - maistas kūnui, protui ir sielai

- 404.txt
Kartas nuo karto parašo koks draugas su prašymu padėti išsirinkti dviratį. 
Aš pats jaučiuosi, kad keičiu dviračius daugiau, nei juos minu, bet atrodo visai turiu susidėliojęs vaizdą kaip rinktis dviratį, tad norėčiau tuo ir pasidalinti.
Kaip išsirinkti pirmą ar antrą dviratį? 
Koks “brandas” geriausias? 
Koks geriausias dviratis duotame biudžete? Kokio dydžio dviračio man reikia? 
Shimano ar Sram? Ką duoda aukštesnio lygio komponentai?
Ratlankio stabdžiai ar diskiniai? Mechaniniai ar hidrauliniai?
Ar reikia kuo daugiau bėgių?
Kodėl grandinės užknisa?
Karbonas, aliuminis, plienas, titanas?
Kalnų dviratis tik kalnams?
Ar bus patogi sėdynė? 
Drop-bars (“ragai”) nepatinka, nepatogu.
Skauda blauzdas, kelius, hamstringus?
Tirpsta rankos?
Bikefit svarba. 
Elektriniai dviračiai tik tinginiams? …
> Kaip išsirinkti dviratį

- 404.txt
Pristatysiu naują inovatyvų įrenginį – robotinę/automatinę blynų keptuvę.
> Blynų robotas

- 404.txt
Pernai gana garsiai nuskambėjus vieno lietuviškojo kavinių tinklo istorija - jau kiek užmiršta, bet privedė prie gana smagaus kolektyvinio kapstymosi ir išvadų apie ganėtinai "efektyvų" EU lėšų įsisavinimą vienos iš rusų kompanijos rankomis. Paburnosiu ir perbėgsiu per kiek platesnį kontekstą ir krūvelę panašių bei tiesiogiai susijusių pavyzdžių. Galbūt bus norinčių paardyti APK? :} Androiders - highly welcome.
> add: Vieno ruskių app'so istorija. Arba kaip įsisavinti EU lėšas.

- 404.txt
Kaip ir kas metus, norintiems išbandyti šį japonišką meną bus origami popieriaus ir lankstymo instrukcijų, nuo paprastų lankstinių iki sudėtingesnių.
> Origami workshopas

- 404.txt
Prieš ~metus įsigijau trial motociklą ir dabar noriu skleisti šitą gėrį. Papasakosiu, kas tai yra, kas tai nėra bei kodėl rekomenduočiau trials ir kaip pirmą motociklą, ir kaip priedą prie turimos patirties.
> Moto trials - smagiau, saugiau, pigiau, daugiau progreso

- 404.txt
In this presentation I'll tell my tale of how I upgraded my RC plane with an autopilot and video streaming. I'll tell what I used, share tips&tricks for building and using such setup and how I did [not] sunk it in Skaistis lake.
> RC plane upgrade with an autopilot and video streaming

- 404.txt
Tėvai pakraupę nuo mano bandymų auginti visokias daržoves bute, nusprendė padėti "upgreidinti" mano kančias iki augalų auginimo tikroje žemėje (the old way). Tėvukai perleido sodą. Sode kokius 5-9 metus "nėravėta". Man labi patinka daržovės, ypač kai pačios auga neprižiūrimos. Izoliuotoje aplinkoje (pvz hidroponikos sistemoje) auginti tingiai (beveik) įmanoma, o kaip tingiai auginti žemėje, po atviru dangum ? Papasakosiu kokį planą turėjau, kaip sekėsi vykdyti ir kokių įrengimų/įrenginių teko susimeistrauti. Na ir atskleisiu kodėl pupeles auginu ;-)
> Tingios pupelės: kaip informatikas pupeles auginti bando

- 404.txt
Ar esi pasiruošęs išlaisvinti savo vidinį genijų ir pastatyti tvirčiausią tiltą? Naudodamas labiausiai tiltui tinkamas medžiagas: spagečius, karštus klijus, izoliaciją ir siūlus (medžiagos bus vietoje) sukonstruok tiltą kuris atlaikys ne ką kitą, o alaus (ar vandens) svorį!
Iššūkio taisyklės:
- Konstrukcija: Tiltą gali statyti tik iš duotų medžiagų: nevirtų spagečių, karštų klijų, izoliacijos ir siūlo/virvelės.
- Matmenys: Tilto galai turi laisvai remtis ant atramų, tarp kurių atstumas – 750 mm.
- Metalinė plokštelė: Tilto konstrukcijoje privalai įtvirtinti duotą metalinę plokštelę (2x40x60 mm) su kabliuku, ant kurio bus kabinamas svoris.
- Masė: Tavo tilto konstrukcija (be plokštelės ir kabliuko) negali sverti daugiau nei 500 g.
- Tvirtumas: Laimi tas, kurio tiltas "pakels daugiausia …
> Spagečių tilto iššūkis

- 404.txt
Imagine a world where politicians never sleep, make decisions based on facts, and can't be swayed by fancy dinners. That's the goal of the AI Party Project in Lithuania. We're creating the country's first political party run entirely by artificial intelligence. Our AI ministers work around the clock, using data to make choices instead of listening to lobbyists. Everything is out in the open, with transparent prompts and public workflows. It's time to give AI a helping hand in running things, because these smart machines need our support to make a real difference in government.
During this presentation I will demonstrate how it is possible to simulate work of a political party/government with some basic code and prompts. This will include simulation of a meeting which results in head of …
> Let's create LLM party to replace Lithuanian government

- 404.txt
Tikriausiai ne kartą miesto parkuose matėte žmones žaidžiančius kažkokį keistą žaidimą - "kamuoliuko daužymą į batutą" Susipažinsime su žaidimo taisyklėmis ir išbandysime praktiškai. Bus prakaito.
> SpikeBall aka Smūginis

- 404.txt
Genų inžinerijos pagrindai - kaip gaminamas insulinas.
> Genų inžinerijos pagrindai - kaip gaminamas insulinas

- 404.txt
Pristatys Bžik:
Aptarsiu savanorystės formas Lietuvoje ir pasaulyje, žmonių motyvaciją, ir egoistines priežastis dėl kurių pati savanoriauju.
> Savanorystė. Kam man to reikia?

- 404.txt
- index.html
Šiais metais kviečiame daryti 3D planetų sistemų modelius!
> Kosminės meno dirbtuvės

- 404.txt
Late PR on 404 kitchen.
https://docs.google.com/presentation/d/1iotnyIBgKOQTM35qvq_3g4fEOiUjbcsalcxYKO80E54/edit?usp=sharing
https://www.youtube.com/watch?v=U6p8qHs8WGA
Modifications from recipe:
- It was not blended - instead we've used more potatoes to create mass and viscosity
- Added smoked salt
- Added can of crushed tomatoes and reduced the hell out of it
- Added black cumin seeds as garnish for enriched eastern flavour profile
https://www.freshoffthegrid.com/tortellini-soup/
Modifications from recipe:
- Used traditional dumplings instead of tortellini (They must be parboiled separately. Otherwise they would release a lot of unwanted starch into stock)
- Added smoked paprica 
- Added Jelapeno flakes (Must be well toasted)
https://amandaoutside.com/sloppy-joes-recipe/
Modifications …
> You Suck at Cooking

- 404.txt
> [!NOTE]
> This has been proposed to the last years camp (https://github.com/ntacamp/404.notrollsallowed.com/pull/255) but I got ill and did not participate.
A follow up to two year old https://github.com/ntacamp/404.notrollsallowed.com/pull/169 talk where I talked about building an [OpenMower](https://openmower.de/).
Now I have been using OpenMower for two seasons and I will talk about:
* building monitoring stack for the OpenMower
* troubleshooting GPS and WiFi connection issues
* new features of OpenMower that have been added since
* new tools that have been created in the OpenMower ecosystem
https://github.com/ntacamp/404.notrollsallowed.com/assets/422086/c7a71536-7462-4991-a871-c028a6771b9f
> Using autonomous 2cm precision GPS lawnmower for two years

- 404.txt
Last year I showcased (#247) my open source silicon project (https://github.com/rtfb/tt05-collatz). However, at that time I had it freshly delivered to me and I didn't have it tested.
This time I will present how I tested it and what I found, as well as some more in-depth overview of how that project works.
> An update to Collatz@TT05 project

- 404.txt
Skamba keistai, bet tyrimai rodo, kad mirusiųjų žmonių portfeliai pasiekė įspūdingų rezultatų. Ko iš to galime pasimokyti investuodami, kol esame gyvi?
Į akcijas ir NT investuoju virš 15 metų. Rašau ir žurnalui „Investuok“. Pristatymo metu pasidalinsiu praktiniais patarimais ir pavyzdžiais.
> Kodel geriausi investuotojai - mire investuotojai?

- 404.txt
Čia renkasi tie, kurie užaugo tarp CRT monitorių ir gyvenimo be pelės.
Čia renkasi tie, kurie instaliavo Linux iš flopikų ir kompaktų.
Tai šventė tiems, kurie žino, kad GUI yra silpniems.
„Terminalo kultas“ – tai valanda, kurioje pasirodo tikri shell’o šamanai.
---
Kulto apeigos tai 30-60 minučių trukmės sesija, skirta trumpiems pranešimams. Pristatinėti gali bet kas, norintis pademonstruoti savo įrankius, įgūdžius ar kūrinius, veikiančius komandinės eilutės rėžime. Tavo pristatymas gali trukti, kad ir 5 minutes, bet ne ilgiau, nei 15. Brolija reikalauja ne iškalbos, o idėjų, minčių ir įgūdžių!
- **Apeigų laikas**: Penktadienis, link pabaigos. Veikiausiai, paskutinis pranešimas.
- **Apeigų trukmė**: 30-60 minučių. Priklausomai nuo to, kiek sulauksime pranešėjų.
- **Pranešimo trukmė**: …
> Terminalo Kultas

- 404.txt
Pristatymas & Workshop
Pristatymo metu:
Kas yra Istoriniai Europietiški Kovos Menai (IEKM/ HEMA - Historical European Martial Arts)
IEKM yra praktiškai visi Europoje kadaise praktikuoti ir bent kiek užrašyti kovos menai, tiek ginklinės sistemos ir tiek beginklinės sistemos, su šarvais ir be šarvų.
Be to papasakosim apie IEKM ir Rekonstruktorių (kovotojų) skirtumus.
Workshop metu:
Ilgojo kalavijo kovos meno pradmenys pagal vokiško fechtavimo tradicijas, jeigu norinčių bus galėsim suorganizuoti turnyrą.
Daugiau info Lietuvos klubam: iekm.lt
> Istorinis fechtavimas ilguoju kalaviju

- 404.txt
Arba "vibe coding" - kaip tai veikia kaip pramoga (žaidimas ar eksperimentavimas savo uždaroje aplinkoje) ir didesnėse kodo sistemose palaikant ir keičiant egzistuojančius projektus.
Kaip keitėsi mano skepticizmas per pastaruosius metus, ir ko vis dar nedaryčiau.
> Jausminis programavimas

- 404.txt
Artificial Intelligence (AI) powered by Machine Learning (ML) models seems ubiquitous today. In reality, these models typically run in the cloud on expensive, specialized hardware. To make ML work on small, low-power devices, we need to make it much more efficient. These devices often use simple binary logic, like XOR. In this talk, I’ll show how we can use that kind of logic to run ML tasks using very few resources.
> Trainable Logic Gate Networks

- 404.txt
Mano asmeninės patirtys dalyvaujant Lietuvos šaulių sąjungoje. Ko tikėtis, ir ko ne? Kas sunkiausia? Ar daug laiko reikia? Ar nepakanka reguliarios kariuomenės? Ką aš it'šnikas galiu išvis duoti? Ir visi kiti klausimai, kurių nerasite googlindami.
> Ką reiškia "būti šauliu"? Apie šaulystę atvirai

- 404.txt
I was always fascinated by [Personal Knowledge Management](https://en.wikipedia.org/wiki/Personal_knowledge_management) tools.
But only [last NTA talk](https://github.com/ntacamp/404.notrollsallowed.com/pull/251) inspired me to actually use PKM tools daily. Both at work, and at home.
My talk will mostly cover:
* Pessimistic privacy in the age of AI
* Verbose communication style
* One tool to rule them all, or honor mix of specialized ones
I will not try to sell [LogSeq](https://logseq.com/) over [Obsidian](https://obsidian.md/), or even over _paper and pen_.
[LogSeq](https://logseq.com/) is just one [of many PKM tools](https://www.pkmweekly.com/).
The concepts behind those tools should be the most interesting part.
> LogSeq: just another Notepad?

- 404.txt
Lituosim viską ir visaip. Pradedantiesiems: LED board'ai, FM imtuvai, mirksiukai.
Pažengusiens: skaičiuotuvai, fidget spinner'iai, tetris game (new)
Ekspertams: signalų generatoriai, mini oscilografas,
> Soldering workshop 2025

- 404.txt
Prezentacija apie elektroninį naktinio dangaus stebėjimą – astrofotografiją.
Kaip fotografuojami ūkai, galaktikos ir kiti giliojo dangaus objektai? Kokios įrangos tam reikia, kaip ją susirinkti, automatizuoti ir naudoti? Parodysiu realius rezultatus bei paaiškinsiu, ką galima pasiekti net iš savo kiemo.
> PR318 Astrofotografija: Kaip veikia elektroninė astronomija?

- 404.txt
PR319 Buriavimo burlente teorija ir praktika.
- atsivešiu naujokams tinkamą burlentę
- papasakosiu kaip ji veikia, kaip ja plaukti,kaip viaruoti
- keli žmonės (pagal laiką ir orą) galės realiai išmokti buriuoti
> PR319 Buriavimo burlente teorija ir praktika.

- 404.txt
- index.html
Aš atsivešiu pjaustymo ploterį, kaitinimo presą ir spalvotų plėvelių. O jūs atsivežkite tuščių marškinėlių be užrašo. Juos galima nusipirkti „Pepco“ po 3 €, o geresnius – „H&M“ parduotuvėse po 5 € (bent jau anksčiau taip buvo). Taip pat susiraskite norimą dizainą ir pasiruoškite. Geriausia ieškoti juodai balto silueto.
> Kaip visada maikonų workshopas

- 404.txt
Užsukite pasipuošti laikina tatuiruote! Turime įvairių raštų ir spalvų - tiek vaikams, tiek suaugusiems.
> Tatuiruočių stotelė

- 404.txt
Kaip LRT žurnalistai sužino tiek daug, turėdami tiek mažai? Atsakymas: atvirieji šaltiniai. Niekas nuo jų nesate saugus, bet galite sužinoti ką veikia kaimynas. If you’re into that sort of thing.
> Atvirųjų šaltinių žvalgyba ir tyrimų žurnalistika.

- 404.txt
Paruošiau GERĄ pranešimą darbe apie konvejerių sistemą kurią kūrėme 2024m. Tikrai tiks ir camp'ui.
> Pranešimas apie sandėlį, robotus ir konvejerius

- 404.txt
Penktadienį dieną bus WS - laivų dronų vandens mūšis. Jei spėsim 2vs2 laivai, 4 dalyviai vienu metu. Numatyta penktadienį. Jei liks sveikų laivų - galima bus pakartoti šeštadienį.
> Laivų dronų mūšis

- 404.txt
Sklandymo patirtys ir vilionės, įskaitant iš šitos kelionės: https://www.youtube.com/watch?v=Rc-IphXg99s Dar bus galima pakalbėti apie 7ių sluoksnių PCB projektavimą ir įvedimą į tarptautinę rinką (nesėkmingai). Bet čia jeigu bus klausiančių.
> Sklandymas - geriau 1000km be variklio ar akrobatika su +6, -4G

- 404.txt
"O tai jūs, ką, gal dar ir dantis šunims valot?" - šitą klausimą girdėjom kokius 50 kartų. Nesam veterinarijos ekspertės, bet auginame šunį su probleminiais dantimis, todėl iš visokių pakampių prisigaudėm žinių, patarimų ir mitų, kaip (ne)reikia rūpintis šunų dantimis. Jais ir pasidalinsim; ir, priklausomai nuo visokių sąlygų, galbūt pasirodys ir tas egzempliorius, nuo kurio šita kelionė prasidėjo.
> Šunų dantų priežiūra 101

- 404.txt
Dirbau 2007-2008 m. Scientific American lietuviško leidimo vertėju ir  redaktoriumi. Prenumeruoju dabar e.versiją. Žaidžiau su Gemini pasidarydamas lietuviškas santraukas: https://app.simplenote.com/p/bvR8NC  Naują versiją padarysiu renginiui ir papasakosiu kas įdomaus.
> Moksliuko nuotykiai su Scientific American ir Google Gemini

- 404.txt
Kepsime molyje įvyniotus mėsos kepsnius laužo žarijose/smėlyje. Bus galima pasmaguriauti mūsų ainių naudotu metodu pagamintų kepsnių ir padiskutuoti apie senovės Lietuvių virtuvę. Kaip ir kada tai vyks teiraukitės lauko virtuvėje.
Ryčka ir Tomas
> Ale viduramžių mėsgalis molyje

- 404.txt
Pranešimas apie tai kaip turėti vešlų, žalią ir derlingą sodą/daržą be trąšų.  Dalinsiuosi, kaip galima greitai (per metus) paruošti geros kokybės kompostą iš buitinių augalinių ir ne tik atliekų. Apie kovą su kenkėjais natūraliais būdais.
Apie augalų derinimą tarpusavyje vienoje lysvėje.
> Eko sodas, greitas kompostas ir augalų sinergija

- 404.txt
Bedarbystės metu išsikroviau fermentuodamas dalykus. Gauromečio fermentacija (klaidos).
Naminio vyno gamybos pamokos ir degustacija.
Kimči.
Kombuča ir pasidalinimas grybo "vaikais" užsikabinusiems. Rauginti kopūstai.
Rauginti agurkai.
Dalinsiuosi receptais. Patirtimi. Mažais, bet svarbiais, retai aprašomais triukais ir gudrybėmis.
> Kai bedarbis atranda fermentaciją

- 404.txt
**Kristina** papasakos ką bendro turi filmas „Jurassic Park“, DIY projektai ir butas Vilniuje? Jei trumpai 🦖➡️🐔pasakosiu apie gyvenimą su vištike Neko (na ir ją parodysiu) ir keliamus iššūkius. Neko (jap. kalba katinas) yra kažkas tarp katino ir šuns, tik su plunksnomis. Jos gyvenimas su manimi, eksperimentai, vištukų elgsenos tyrimai ir bei dresūra. Ir žinoma kelionės - Neko keliaujanti vištuke.
> Gyvenimas su miniatiūriniu tiranozauru (t.y. vištuke)

- 404.txt
Kol tėčiai ir mamos kultūrinasi, vaikus gerai užims muilo burbulai.
Turėsime keleta kibirų skysčio ir įvairaus dydžio lazdų ir lazdelių muilo burbulų pūtimui.
Su didesnėmis lazdomis vaikai dažiausia "pučia burbulus" tiesiog bėgdami.
Jei turėsite ir savo muilo burbulų buteliuką – irgi prisijunkite į burbulų fiestą.
> Dirbtuvės: Dideli muilo burbulai

- 404.txt
**Laima** praves muzikinį protmūšį
---
Tikiu, kad Trolių bendruomenėje turim nemažai įvairios muzikos gerbėjų, o ir pati esu viena iš jų. Pastaraisiais metais dalyvavau ne viename muzikiniam protmūšyje, kur galbūt rezultatai nebuvo patys geriausi, bet kiekvieną kartą išsinešdavau kažką naujo. Taigi, kviečiu visus muzikos entuziastus patikrinti savo žinias, o galbūt ir atrasti dar negirdėtų gabalų ir praturinti savo playlist’us. 
Kad neužtruktumėme per ilgai, protmūšį sudarys 2 turai - žinias tikrinsime lietuviškos ir užsienietiškos muzikos pasauliuose. Komandų limitą ir žmonių skaičių jose patikslinsiu vietoje.
> Muzikinis protmūšis

- 404.txt
Esu lietuvių kalbos egzamino šimtukininkė ir dviejų Nacionalinio diktanto finalų dalyvė. Nors dirbu energetikos ir IT srityse, taisyklinga kalba – mano super galia. Kasdien matau, kaip žmonės kartoja tas pačias kalbos klaidas, nors jų galima lengvai išvengti pasitelkus kelias paprastas taisykles (tikrai paprastas – be linksniuočių ir kirčiuočių!).  Mano pranešimas neprimins lietuvių k. pamokos 😊 Noriu lengvai ir su _memes_ pasidalyti įdomybėmis apie kalbą, naudingais šaltiniais ir pakviesti diskusijai: kodėl turėtume kalbėti taisyklingai, net jei esame inžinieriai, hackeriai ar sysadminai?
> Kaip rašyti be klaidų

- 404.txt
Pirmą kart dalyvaučiau, tai kol kas norėčiau papasakoti apie psichologinės nuosavybės jausmą, kurį nagrinėju savo akademinėje veikloje. 
Kaip prisirišam prie dalykų, kurių fiziškai nelabai yra, ką su tuo galime nuveikti kalbant apie 
a) motyvacinius dalykus
b) vertę stakeholderiams (klientams, vartotojams, kolegoms)
c) prasmės klausimai (pvz ką daryt su tuo noru kaupti saugoti dalykus)
Padiskutuoti apie tai kur vertė bus išgaunama ateityje, kai kodas bus komoditizuojamas.
> Psichologinė nuosavybė: oras, kodas ir mokslas

- 404.txt
Išmokę ankstensnių metų pamokas ir pasiruošę sausesnių malkų, pabandykime dar sykelį išsukti NTA šakotį.
Kadangi procesas ilgas ir varginantis, nesibodėkite prisijungti ne tik prie degustacijos, bet ir viso gamybos proceso.
Susitiksime bendros virtuvės teritorijoje, prie pečiaus :)
Povarai - Paulius ir galimai bent trumpam prisijungsiąs Algirdas.
> Šakočio tešlos maišymas, kepimas ir degustacija

- 404.txt
Trumpas pasakojimas apie pianino klavišų apšvietimą pagal natas ir kaip tai pasidaryti pačiam. ESP32 + WS2812B + biški kodo.
> Kai natas skaityti sunku, o groti norisi

- 404.txt
Po burbėjimo metų metus, šioks toks motyvacinis pa-si-pa-sakojimas apie kontribucijas atviro kodo projektams. Tiek kalbant apie kodą, tiek apie kitas galimybes. Apskritai, ką prasmingo galima nuveikti nūdienos skaitmenoje, dažnai kylančios susiję problemos ir demotyvacijos bei sėkmingi ir ne itin sėkmingi pavyzdžiai.
Bendrai, mano tikslas šiuo pranešimu, priminti tautiečiams, ant kokių snarglių laikosi mūsų mėgiami, o gal ir pamiršti, įrankiai ir ką prasmingo galima nuveikti užpildant vis atsiverenčias tuštumas.
> Pa-kontributinkim: atviro kodo bei duomenų bad, good & ugly

- 404.txt
Atsivešiu seną dual sport Honda Dominator traktoriuką, parodysiu basics. Priklausomai nuo įgūdžių (ar kaip greitai seksis juos įgyti) bus galima apvažiuoti ratuką aplinkiniais keliukais. Duosiu šalmą (jei tiks dydis), didelius enduro batus, kažkiek kitų apsaugų. Norint jautis patogiau, rekomenduoju turėti kažkokius tvirtesnius savo dydžio batus (aukštesnis aulas geriau).
Galbūt bus ir antras, tris kartus lengvesnis motociklas.
> Atsisėsk ant off-road motociklo

- 404.txt
Idėja jau kelis kart išbandyta KMS. Principas paprastas: Yra nedidelis, bet pasiutusiai garsiai rėkiantis savadarbis turboreaktyvinis variklis, kuris yra kūrenamas paprastomis buitinėmis dujomis, todėl į jo išmetamų dujų srautą įkišus zefyrą galima jį iškepti ir valgyti. Jei galima būtų gerai kurti panašiu metu kaip pulsoreaktyvinį variklį (irgi iš KMS), tiesiog nes jei darom triukšma tai darom kartu :). Zefyrus ir pagaliukus nupirksiu. Kiek laiko truks nežinau, nes variklį užkurti ir pašildyti reikia bent 10 min. Ar miške, kur nėra galingo kompresoriaus, pavyks užkurti irgi nežinau, bet girdėjau nusivežė KMS orpūtę, tai su ta užsikurs tikrai. Bus daug triukšmo, bet klausos apsaugos visiems tikrai neturėsiu, todėl žiūrovams patartina laikytis saugaus atstumo, nebent turi apsaugą arba …
> Workshop: zefyrų kepimas su turboreaktyviniu varikliu

- 404.txt
Self-hostint backupus dažniausiai reiškė rsync komanda crontab'e. Geriausiu atveju incremental'iškai siunčiant backupus (neatomiškai) pražiūrint visą diską (ar backup folderį).
"Next-generation" failų sistemos kaip zfs, btrfs padaro paradigm shift'ą, kur galima daryti failų sistemos snapshots failų sistemos levelyje.
Pakalbėsiu apie patirtis naudojantis btrfs, bei esančius atviro kodo backup įrankius, bei kaip supratau kad nėra gero, tai prikėliau vieną projektėlį (snapsync) ir pridėjau galimybes siųsti backups remotely, galiausiai perrašiau pytonu ir toliau gerinau.
> Presentation: Happy Backups wit Btrfs
